### ISSUE TITLE
TT4: Initial commit

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/twentytwentyfour#1]
The theme has been exported directly from the editor where it was originally designed and it's in a raw state. This initial commit is the source of truth for the design, since there were some adjustments made directly in the editor when translated from the figma file.

Let's clean this up in small PRs for each task or template affected. The list of tasks to be done includes:

- [x] Clean up of theme.json file since the exporter adds some redundant rules. There will be additional issues for code quality changes such as fluid typography, reviewing the units used for spacing, adding rules that can´t be changed directly in the editor yet (such as hover for the buttons), etc.
- [x] Abstract block patterns from the templates 
- [x] Discuss renaming of the templates/patterns
- [x] Move to patterns anything that has either text that needs i18n or images that need their URL to be dynamic
- [x] Clean up the readme.txt file that is coming from the base theme used as a base
- [x] Discuss the contents of the style.css file
- [x] Discuss the renaming of the alternative templates

**Comment by carolinan** [comment]
I started on the theme.json cleanup.
