### ISSUE TITLE
Style Variations

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwentyfour#10]
There will be three additional style variations available:

- [x] Default - Light Serif
- [ ] Dark - Serif
- [ ] Light - Sans-Serif
- [x] Dark - Sans-serif

**Comment by melchoyce** [comment]
I'd love to design a variation for Twenty Twenty-Four! Is there a process for community members to submit ideas yet?

**Comment by richtabor** [comment]
> I'd love to design a variation for Twenty Twenty-Four! Is there a process for community members to submit ideas yet?

I'm not one of the leads, but I'm sure PRs are welcome :)

**Comment by richtabor** [comment]
We can probably come up with better names for these. 

Perhaps natural/organic color terms, like "Clay", "Onyx", "Ice", "Sesame", "Dove", "Jade", "Moss" etc. 

Reads a bit less tech and more human perhaps.

**Comment by MaggieCabrera** [comment]
> > I'd love to design a variation for Twenty Twenty-Four! Is there a process for community members to submit ideas yet?
> 
> I'm not one of the leads, but I'm sure PRs are welcome :)

Always!

**Comment by damen02** [comment]
Hello!
I have an idea that I think would be a great improvement on the use of style variations. I don't know if this is the right place to do it.

Currently it is possible to choose only one style variation for all website posts. It would be great to be able to apply a different style variation for different templates or CPTs. I mean changing typography, colors and spacing for each case depending on the type of content.

I can imagine many scenarios in which this would be very useful.
- Let's say you have a clothing store and you want to apply a style to products for babies, another for women and another for men.
- Or let's say you have a magazine and you want to apply a style to all the posts in the sports section, a different style to all the posts in the science section, and another for art, and so on.
- Or let's say you are simply an eclectic artist and you have different kind of works to offer, like paintings, sculpture or virtual.

The idea is not to limit the style variations to a single option, but to be able to use several on the same website, choosing according to the type of content.

Thank you for reading!

**Comment by richtabor** [comment]
> Currently it is possible to choose only one style variation for all website posts. It would be great to be able to apply a different style variation for different templates or CPTs. I mean changing typography, colors and spacing for each case depending on the type of content.

Yes! I think that's an interesting idea for sure. 

Theme.json partials (where you can apply colors—and other styles—to specific areas of a site) is something being explored in https://github.com/WordPress/gutenberg/issues/40318 and https://github.com/WordPress/gutenberg/issues/48581.
