### ISSUE TITLE
Template selection

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/twentytwentyfour#100]
The idea for this theme is to have three possible use cases, hence why we have multiple options for templates like home, page or single. Right now there is no easy way in WordPress to swap an existing template with an alternative provided by the theme in a way that is not manually emptying/deleting the existing template and redoing it. There are some designs explorations for this flow on https://github.com/WordPress/gutenberg/issues/36951#issuecomment-1674411656 and I've discussed this with @richtabor during WCUS and we thought that we could make use of the tools that already exist for Block Patterns.

The idea would be to register these alternate versions of the templates as patterns and make use of [templateTypes](https://developer.wordpress.org/block-editor/reference-guides/block-api/block-patterns/#register_block_pattern) to assign the template that should use this pattern. This already works well for creation of new pages, but we are missing the flow for replacing.

**Comment by richtabor** [comment]
We’d remove these templates as “templates” as well, right? I don’t think we need them front and center here, and as template types. 

We may want them to show up when you add a new page too (without header and footer).

**Comment by dianeco** [comment]
Can we remove the home.html template? It conflicts with the settings saved in WordPress dashboard > Settings > Reading and can confuse the users.

**Comment by richtabor** [comment]
> Can we remove the home.html template? 

Perhaps we need a quick play-by-play on the options we can use for the main page, and how those will interplay with the templateTypes selection above.

**Comment by kafleg** [comment]
> Can we remove the home.html template? It conflicts with the settings saved in WordPress dashboard > Settings > Reading and can confuse the users.

Or we can change home.html to front-page.html?

**Comment by maneshtimilsina** [comment]
Both `home.html` and `front-page.html` will have conflicts with the settings saved in WordPress dashboard >> Settings >> Reading as mentioned by @dianeco

**Comment by richtabor** [comment]
This issue would let us swap out entire templates: https://github.com/WordPress/gutenberg/issues/51347

**Comment by carolinan** [comment]
I do not understand in what way the home template conflicts with the reading settings, as mentioned above. It is the template used to display the blog.

**Comment by maneshtimilsina** [comment]
@carolinan Go to Settings >> Reading and select A static page option for Your homepage displays. Assign pages for Homepage and Posts page. Check both the homepage and blog post page. I think one of them will not work as expected.

**Comment by carolinan** [comment]
I made the test, and both the blog and the actual front page display the correct content.

**Comment by dianeco** [comment]
@carolinan In Settings > Reading, I set a static page as my Homepage and my “Blog” page as the Posts page. However, instead of displaying my posts, my Blog page shows a page about architecture (the same page as the homepage of https://2024.wordpress.net/). So, if a user switches their theme to Twenty Twenty-Four, their website will initially display content that is not theirs.

**Comment by carolinan** [comment]
That does not happen on my installation. Please first try to reset any changes you have made to templates, and make sure you are using the latest version of the theme.

**Comment by carolinan** [comment]
Make sure that no other template is "assigned" to the page called "Blog".

**Comment by dianeco** [comment]
I'm testing with Twenty Twenty Four trunk without making any changes to the theme on a fresh WordPress installation. The Blog Home template's description is `"Displays the latest posts as either the site homepage or as the 'Posts page' as defined under reading settings"`. So, it's expected to see the content of the `home.html` (which contains content about architecture) on the Blog page.

![twentyfour instawp](https://github.com/WordPress/twentytwentyfour/assets/44895380/a951f49d-0fb5-4aab-9357-0aa0fae7344f)

**Comment by carolinan** [comment]
And I do see the content of home.html. I am still confused.
The screenshot above is of home.html. The posts are below that.

I think it is working as expected. It is just a matter of different expectations since the template uses the patterns.

**Comment by richtabor** [comment]
@MaggieCabrera It may be good to try templateTypes out with the `twentytwentyfour-page-portfolio-home` pattern, in lieu of the home-portfolio.html template, as an alternate blog home. I think we'll run into a few issues that will be good to iron out early. 

We _may_ need to have a portfolio page pattern _with_ header and footer parts, so it's a proper full replacement — whereas currently the portfolio page pattern is just the content (like other page patterns). We may need both (which shouldn't be a heavy lift, as we're building with pattern blocks anyhow). 

For testing we can just add a new template.

**Comment by carolinan** [comment]
Unpopular opinion: Maybe they should just be child themes.

**Comment by MaggieCabrera** [comment]
> Unpopular opinion: Maybe they should just be child themes.

Not really unpopular, it's another very valid way of doing the same thing. It's still valid that a theme may want to include different versions of a same template (it's something commercial themes have done very often too in the past). I think having this problem means having this discussion, so that's a good thing. 

@richtabor definitely we can add `templateTypes` but my testing of that has been that it doesn't do much more than `Post Types: page` is already doing

**Comment by richtabor** [comment]
> Unpopular opinion: Maybe they should just be child themes.

They're just different page designs; I don't think it's child theme territory.

**Comment by richtabor** [comment]
> @richtabor definitely we can add templateTypes but my testing of that has been that it doesn't do much more than Post Types: page is already doing

@MaggieCabrera In my testing we need to _remove_ "Post types: page" from template patterns (related: https://github.com/WordPress/gutenberg/issues/45859), then they show up in the template choose a pattern selector. 

And we need to do this: 

> We may need to have a portfolio page pattern with header and footer parts, so it's a proper full replacement — whereas currently the portfolio page pattern is just the content (like other page patterns). We may need both (which shouldn't be a heavy lift, as we're building with pattern blocks anyhow).

https://github.com/WordPress/twentytwentyfour/assets/1813435/9359d7f8-c3b8-4285-a79b-002a7ab15fbb


I just used "page" as a template type for the video, but front-page could work maybe.

**Comment by carolinan** [comment]
By removing the template files and by removing full page designs that are similar but are intended to have a different context and footers, it feels like the concept of three different use cases is abandoned.

There is no **easy** way for users to switch both site building templates like the search results page and their content templates (page, post) to the same style: There is no way to switch all templates at once without child themes.

I don't agree that having template files in the Site Editor is confusing. And it is not more confusing than having things like the 404 template show up in the page list...
Especially page template switching is easier in 6.4 with the new template swap when you go to Appearance >Editor > Pages.
**But I don't have real user testing data that points to either patterns or templates being easier.**

I also don't think that having a portfolio template for a non-portfolio site is confusing. If the naming is the problem, then lets rename it.

For example, all custom page and post templates could be clearly named custom, optional, or alternative:
Custom page with sidebar (has no post meta information because it is a page...)
Custom post with sidebar (has post meta)
Custom page with two columns (this is the portfolio where the post title is on the left)

Custom site building templates (custom archives, index, search) can remain patterns since there is no easy way to replace them without deleting the blocks in the existing template).

But I have lots of opinions and I think that the decision must be based on how @luminuu and @MaggieCabrera wants the theme to work.

**Comment by richtabor** [comment]
> And it is not more confusing than having things like the 404 template show up in the page list...

Imagine you have three 404 templates. That’s the comparable here.

**Comment by MaggieCabrera** [comment]
> > And it is not more confusing than having things like the 404 template show up in the page list...
> 
> Imagine you have three 404 templates. That’s the comparable here.

I see this. I get that the list of templates should ideally should show one of each possible option, and then the alternatives should be shown some place else. This is the first time we are offering alternatives to other than the page/single templates, so we are risking polluting that list even more than previous default themes. We need to strike a balance between discoverability and overwhelming the user where he's not expecting.

I'm in the fence here, I think we've already built the expectation of some of the variations to be there (like no title or blank, it feels like we've been adding those templates since forever), but we probably shouldn't push that too much.

**Comment by luminuu** [comment]
What I was originally thinking of how these different content approaches could be implemented was something like this:

![CleanShot 2023-09-19 at 17 26 33@2x](https://github.com/WordPress/twentytwentyfour/assets/7585600/d0355343-7ac8-42ab-8c99-9dcbd9d33171)

These separate templates would have been a dropdown or something and would replace the entire existing template at once. Any default WP view (archive, categories, 404, single) could have multiple different options, or just one default. This would prevent the current "Page Portfolio", "Page Writer" etc on the main templates overview.

But I guess it's now too late already to get something like this done.

**Comment by MaggieCabrera** [comment]
This will be closed by https://github.com/WordPress/gutenberg/pull/54609, which is a blessed task

**Comment by luminuu** [comment]
While it does work with Beta 3, I found out in my testing yesterday it's not working anymore with the latest Gutenberg version installed, I opened an issue: https://github.com/WordPress/gutenberg/issues/55218
