### ISSUE TITLE
Block Patterns - Hero

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfour#107]
**Description**

🛠️ The goal of this issue is to track the implementation of the hero pattern.
🎨 [Figma](https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=536%3A1918&mode=design&t=LHSPHKUrPq556l59-1)

![Hero](https://github.com/WordPress/twentytwentyfour/assets/252415/1cb3040d-3c92-4718-803d-1b122c0023a2)

**Comment by jordesign** [comment]
I'm happy to work on this one
