### ISSUE TITLE
Block Patterns - About

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfour#115]
**Description**

🛠️ The goal of this issue is to track the implementation of the "About" pattern.
🎨 [Figma](https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=492%3A4916&mode=design&t=LHSPHKUrPq556l59-1)

![About](https://github.com/WordPress/twentytwentyfour/assets/252415/a00ed002-3488-424c-a700-fe6294f7077f)

**Comment by jordesign** [comment]
I'm seeing this pattern as already included in the theme?

**Comment by MaggieCabrera** [comment]
Some of them are and need to be extracted from the template into a pattern so people can reuse them, so this issue is relevant

**Comment by jordesign** [comment]
Sorry @MaggieCabrera  - I should have been clearer. What I meant is that I'm already seeing about.php separated into a pattern in the repo.

https://github.com/WordPress/twentytwentyfour/blob/trunk/patterns/about.php

**Comment by MaggieCabrera** [comment]
You are right, sorry! Closed by https://github.com/WordPress/twentytwentyfour/pull/22
