### ISSUE TITLE
Block Patterns - Team

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfour#117]
**Description**

🛠️ The goal of this issue is to track the implementation of the "Team" pattern.
🎨 [Figma](https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=565%3A10409&mode=design&t=LHSPHKUrPq556l59-1)

![Team](https://github.com/WordPress/twentytwentyfour/assets/252415/17629f89-b52f-41d2-a335-3740b9838d89)

**Comment by devmuhib009** [comment]
Just submitted new PR #180
