### ISSUE TITLE
Block Patterns - FAQ

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfour#119]
**Description**

🛠️ The goal of this issue is to track the implementation of the "FAQ" pattern.
🎨 [Figma](https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=565%3A10443&mode=design&t=LHSPHKUrPq556l59-1)

![FAQs](https://github.com/WordPress/twentytwentyfour/assets/252415/620fe05a-3e46-4d7f-a87b-0cc794dfd07e)

**Comment by esrat71** [comment]
Here's  I have a query on mind. I can create pattern with default gutenberg blocks , and love to contribute in this . How can i do this pattern and submit ? any procedure to follow? Have already installed the basic setup on my pc.

**Comment by carolinan** [comment]
To add a new pattern, you must create a new PHP file and save it in the patterns folder.
To add the style to the list block, you will also need to register a custom block style. https://developer.wordpress.org/themes/advanced-topics/custom-block-styles/

Clone the GitHub repository.
Add a new branch.
Upload the pattern to your branch.
Create a pull request to add your branch with the new file to this repository.


---
The fastest way to create a new pattern is to copy an existing pattern and replace parts of it.

For example, if you copy about.php, you need to:
- Rename the PHP file to something that makes sense like faq.php
- Add the correct title, slug, and category
- Replace the code below the file header with your blocks.

But to learn how to build patterns, you should create them from scratch :)
[Documentation about creating patterns
](https://developer.wordpress.org/themes/advanced-topics/block-patterns/)

**Comment by esrat71** [comment]
@carolinan Thank you for your explanation. I  am going to do this pattern . I have found a issue with Separator block style as need as per design . So I  created issue for This.  Now little bit confused  , as separator is not getting expected result how i should submit the design (with separator not visible color ) or should stop working on this ?

**Comment by esrat71** [comment]
@carolinan Thank you for your explanation. I have already created the pattern . and uploaded pattern to my branch. Here i am stuck in pull request . Can you guide me ?

**Comment by carolinan** [comment]
It looks like you already added the pull request correctly.
