### ISSUE TITLE
Block Patterns - Landing Page

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfour#121]
**Description**

🛠️ The goal of this issue is to track the implementation of the "Landing Page" pattern.
🎨 [Figma](https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=565%3A10503&mode=design&t=LHSPHKUrPq556l59-1)

![Landing Page](https://github.com/WordPress/twentytwentyfour/assets/252415/2972cf8b-cb86-4385-9519-3340341e191d)

**Comment by richtabor** [comment]
It's been updated with presets, but the icon is not resolving: 

<img width="1343" alt="CleanShot 2023-08-30 at 13 56 19" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/0e94d17c-f2c3-4ba8-88f3-668eea148589">

**Comment by huzaifaalmesbah** [comment]
I checked another fresh install wp and tt4. working properly. 

<img width="1440" alt="Screenshot 2023-08-31 at 5 28 19 AM" src="https://github.com/WordPress/twentytwentyfour/assets/63150399/8535a19d-41cd-4ae0-9787-1a556df6e429">
<img width="1424" alt="Screenshot 2023-08-31 at 5 27 20 AM" src="https://github.com/WordPress/twentytwentyfour/assets/63150399/d83ea113-ad55-47ba-b572-608bfcef4c5b">
