### ISSUE TITLE
Block Patterns - RSVP

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfour#122]
**Description**

🛠️ The goal of this issue is to track the implementation of the RSVP pattern.
🎨 [Figma](https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=565%3A10707&mode=design&t=LHSPHKUrPq556l59-1)

![RSVP](https://github.com/WordPress/twentytwentyfour/assets/252415/d5b176e4-3db5-4401-af05-f3af8836f10e)

**Comment by richtabor** [comment]
Let's make sure when we're building these out that we build well for mobile. Perhaps trying to leverage Row instead of Columns where it makes sense (maybe here). 

Also, PR's should include screenshots of desktop and mobile.

**Comment by carolinan** [comment]
The text orientation option in Gutenberg is not working that well and is not in core yet.

**Comment by richtabor** [comment]
> The text orientation option in Gutenberg is not working that well and is not in core yet.

@carolinan do you mind linking the PR so we can track. Thanks!

**Comment by carolinan** [comment]
The issues and PR's are in the pinned issue.

The "Upside down" vertical text has been merged into Gutenberg but I still need to make the backport to core, and make it available for the heading block.

**Comment by MaggieCabrera** [comment]
> The text orientation option in Gutenberg is not working that well and is not in core yet.

We can remove the pattern last minute if the feature is not ready
