### ISSUE TITLE
Block Patterns - Project Description

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfour#123]
**Description**

🛠️ The goal of this issue is to track the implementation of the "Project Description" pattern.
🎨 [Figma](https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=565%3A10541&mode=design&t=LHSPHKUrPq556l59-1)

![Project Description](https://github.com/WordPress/twentytwentyfour/assets/252415/f9a7c2da-f4dd-48b5-9cb8-7114a10e610b)

**Comment by jordesign** [comment]
I'll take a run at this one

**Comment by jordesign** [comment]
PR in https://github.com/WordPress/twentytwentyfour/pull/142
