### ISSUE TITLE
Block Patterns - Project Details

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfour#124]
**Description**

🛠️ The goal of this issue is to track the implementation of the "Project Details" pattern.
🎨 [Figma](https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=565%3A10536&mode=design&t=LHSPHKUrPq556l59-1)

![Project Details](https://github.com/WordPress/twentytwentyfour/assets/252415/15cddb86-2d5c-47c4-b757-cb274e0f7aff)

**Comment by khleomix** [comment]
I'm going to work on this.

**Comment by khleomix** [comment]
@juanfra I've been trying to push my branch but I'm getting a permission error:
``` bash
git push --set-upstream origin pattern/#124-Project-Details                    [23/09/4|11:01PM]
ERROR: Permission to WordPress/twentytwentyfour.git denied to khleomix.
fatal: Could not read from remote repository.

**Comment by MaggieCabrera** [comment]
> @juanfra I've been trying to push my branch but I'm getting a permission error:
> 
> ```shell
> git push --set-upstream origin pattern/#124-Project-Details                    [23/09/4|11:01PM]
> ERROR: Permission to WordPress/twentytwentyfour.git denied to khleomix.
> fatal: Could not read from remote repository.
> ```

You need to make a fork of the repo to make your first PR first

**Comment by khleomix** [comment]
Thanks @MaggieCabrera I'm on it.

**Comment by khleomix** [comment]
@MaggieCabrera I saw the markup you added in #188 would you want me to follow that markup for this pattern instead? Figma shows the heading as Extra Large but the preset is larger (3rem) than that of Figma which is 2.375rem (38px). The markup shows an extra empty column, do we need that and what's the expectation for that column? Allow people to add in additional content in between?

**Comment by MaggieCabrera** [comment]
> @MaggieCabrera I saw the markup you added in #188 would you want me to follow that markup for this pattern instead? 
 
Let's use it as a base, but we can iterate on it if need be

> Figma shows the heading as Extra Large but the preset is larger (3rem) than that of Figma which is 2.375rem (38px).

Looking at the design for the overall pattern, the font sizes between three different templates need to be the same here to keep it consistent. Let's check the markup of the patterns that have been already created and make sure they are all the same. It looks like that is a big difference, so I would probably use a hardcoded value here 

> The markup shows an extra empty column, do we need that and what's the expectation for that column? Allow people to add in additional content in between?

I think this could be different ways of approaching this pattern. Which one looks better on mobile? As long as the end result looks like the design, I'm happy with some tweaks
