### ISSUE TITLE
Footer text "Designed with" is not visible.

### ISSUE THREAD

**Issue by labunchemjong** [WordPress/twentytwentyfour#146]
**Description**
While testing Twenty Twenty Four theme, I found that the Footer text "Designed with" is not visible.

![footer-text-not-visible](https://github.com/WordPress/twentytwentyfour/assets/12745968/46312b2a-2a56-44e0-9efd-f9bf4618f549)

**Comment by kafleg** [comment]
This class is causing issues, 
![image](https://github.com/WordPress/twentytwentyfour/assets/13062231/94cf8d66-04f6-4109-84cb-ee78c513bbbb)

**Comment by huzaifaalmesbah** [comment]
thank you for reporting this issue

**Comment by maneshtimilsina** [comment]
Fixed here https://github.com/WordPress/twentytwentyfour/pull/147

**Comment by MaggieCabrera** [comment]
I don't think this is happening anymore but please reopen if you see it again
