### ISSUE TITLE
Block Pattern Bug: Default button is inaccessible when in editing mode

### ISSUE THREAD

**Issue by aurooba** [WordPress/twentytwentyfour#151]
**Description**

When you click to edit a default button, the background turns transparent and the light text is unreadable.

**Step-by-step reproduction instructions**
1. Create a new page or post
2. Add a button block
3. See that you can't see anything, but if you click away or on a different block, you can see the block

**Expected behavior**

The dark background remains so you can see the text you're editing.

**Screenshots**

![hover-bug-on-button](https://github.com/WordPress/twentytwentyfour/assets/6925260/817a478d-ee12-47af-8e20-64d9d997b80c)

**Environment info**
Please share the browser(s) are you seeing the problem on.
Please share the Device you are using and operating system (e.g. "Desktop with Windows 10", "iPhone with iOS 14", etc.).
 - Device: Mac
 - OS: Mac OS 12.6
 - Browser: Arc Browser
 - Version: 1.5.1

**Comment by devmuhib009** [comment]
❌ I just tested and found same issue on Windows.

Environment info
Device: Lenevo Ideapad 320
OS: Windows 11
Browser: Google Chrome Browser
Version: 116.0.5845.110 (Official Build) (64-bit)

**Comment by alaminfirdows** [comment]
I'm working on it

**Comment by alaminfirdows** [comment]
https://github.com/WordPress/twentytwentyfour/pull/165

I have submitted the PR and am looking forward to receiving feedback.
