### ISSUE TITLE
Seperator style default and wide color is not visible in black background 

### ISSUE THREAD

**Issue by esrat71** [WordPress/twentytwentyfour#152]
**Description**
 While testing Twenty Twenty Four theme faq section as black background , I found that the separator color is not visible and found dots style taking the color also but others are  not

**Step-by-step reproduction instructions**

1. Add a section or group with black background
2. Add Separator block and try to give a background color 
3. change the style to check all the style

**Expected behavior**
separator color should be visible as the color i give.

**Screenshots**
https://www.loom.com/share/6cd2a84b331d4944aa054b82b2d29912?sid=66f4d9a9-b6ad-4345-86d7-bae0ee792704

**Environment info**

Please share the browser(s) are you seeing the problem on.
Please share the Device you are using and operating system (e.g. "Desktop with Windows 10", "iPhone with iOS 14", etc.).
 - Device: Mac OS
 - OS: Apple M1
 - Browser: Google Chrome
 - Version:116.0.5845.110

**Additional context**

**Comment by devmuhib009** [comment]
**Test Report**
✅ In my setup, it's working fine. I just tested on Windows Computer and the separator is visible. I tested in default mode, wide angle mode and dot mode as well.

Here is the [screenshot](https://prnt.sc/vS9LwVZPHJzG), in case you want to check.

**Environment info**

Device: Lenevo Ideapad 320
OS: Windows 11
Browser: Google Chrome
Version: 116.0.5845.110 (Official Build) (64-bit)

**Comment by esrat71** [comment]
> **Test Report** ✅ In my setup, it's working fine. I just tested on Windows Computer and the separator is visible. I tested in default mode, wide angle mode and dot mode as well.
> 
> Here is the [screenshot](https://prnt.sc/vS9LwVZPHJzG), in case you want to check.
> 
> **Environment info**
> 
> Device: Lenevo Ideapad 320 OS: Windows 11 Browser: Google Chrome Version: 116.0.5845.110 (Official Build) (64-bit)

Yes, I have already checked. It's working fine for group item. Have you tried using stack item as i have shown in video?

**Comment by devmuhib009** [comment]
❌ I did not use on stack. Just checked after your comment and it's not working. Your issue is valid.

**Comment by hanneslsm** [comment]
Probably the same issue: https://github.com/WordPress/gutenberg/issues/47993

**Comment by MaggieCabrera** [comment]
This issue is not specific to TT4, so let's continue giving feedback in the GB issue. Thanks for reporting!
