### ISSUE TITLE
Buttons are disappeared in Focus Mode

### ISSUE THREAD

**Issue by zakariabinsaifullah** [WordPress/twentytwentyfour#153]
**Issue**
When I clicked on the buttons and moved my mouse cursor, I found the buttons' texts had disappeared. When the focus mode is active, the text color goes to white, since the background color is also white, that's why the text disappears. 

**Expected behavior**
when the buttons are in Focus mode like :focus,  The text color should be different from the background color. For example, the text color should be Black. 

**Screenshots**

![issue](https://github.com/WordPress/twentytwentyfour/assets/30005639/e3bf4ef8-4563-49f6-a810-38a1a2e9e2ee)

**Environment info**
I have tested it on the Google Chrome browser

**Comment by alaminfirdows** [comment]
I'm working on it
