### ISSUE TITLE
Date and Author Archive links missing in Blog Home Page

### ISSUE THREAD

**Issue by zakariabinsaifullah** [WordPress/twentytwentyfour#154]
**Description**
The date and Author archive page links are missing. Only the category archive page link is working fine.

**Expected behavior**
Visitors should be able to see the date archive page by clicking on the date, so the post date should be linked with date archive page. Similarly, the author's name should be linked with the author's archive page

**Screenshots**
![archive](https://github.com/WordPress/twentytwentyfour/assets/30005639/048d6025-5cf0-41b6-9aa3-5627e8e1ca58)

**Comment by alaminfirdows** [comment]
Working on this one
