### ISSUE TITLE
Styles variations like twentytwentythree theme

### ISSUE THREAD

**Issue by zakariabinsaifullah** [WordPress/twentytwentyfour#155]
I think it'd be better if you could add style variations under the Styles menu in the site editor like the twentytwentythree. See the screenshot:
![styles](https://github.com/WordPress/twentytwentyfour/assets/30005639/32e6add5-6734-438c-be0c-37dd604877e1)

**Comment by carolinan** [comment]
Hi,
Yes, there is an issue and two pull requests for these already, please see https://github.com/WordPress/twentytwentyfour/issues/10
