### ISSUE TITLE
Services CTA pattern is almost hardcoded

### ISSUE THREAD

**Issue by maneshtimilsina** [WordPress/twentytwentyfour#164]
**Description**

Spaces, background, font, font weight, etc of the Services CTA button are hardcoded. 

**Step-by-step reproduction instructions**

1. Go to 'patterns >> services-cta.php'
2. Check the code of the pattern one by one.

**Expected behavior**

Instead of arbitrary values, let's use the presets for the background, font, paddings, font size, font weight, etc.

**Comment by esrat71** [comment]
yes i have checked the code. most of are seem to be hard coded
