### ISSUE TITLE
Disable 2024.wordpress.net git pull

### ISSUE THREAD

**Issue by kraftbj** [WordPress/twentytwentyfour#173]
The 2024.wordpress.net site is automatically updated via `git pull` to stay up to date with this repo. When the canonical source of twentytwentyfour is moved to SVN and updates via the regular theme updates is the way, we need to disable the cron.

Adding this now to not forget it totally. If I don't comment here when the move happens, please someone ping me here :)

This issue should be marked `[Type] DevOps` and whatever status label is proper for a blocked/on-hold item. Thank you!

**Comment by MaggieCabrera** [comment]
@kraftbj I think now is the time!
