### ISSUE TITLE
Consider using a modern font stack instead of system fonts

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentytwentyfour#175]
Several default themes are using system fonts. This is a great practice since they have great language support and it avoids loading several font files. A disadvantage is that they are often not very similar on different operating systems (OSs).

An interesting alternative would be to use a modern font stack. It has the same advantages as a system font stack, but in addition they are chosen to **match better between different OSs**.

The [modern font stacks website](https://modernfontstacks.com) showcases several ideas. For example, the Neo-Grotesque stack could be a great alternative to where the theme now uses system fonts. The GitHub repo of the project demonstrates [how this stack looks](https://github.com/system-fonts/modern-font-stacks#neo-grotesque) in different OSs.

**Comment by beafialho** [comment]
Thank you for the recommendation! I think the Neo-Grotesque stack would be a good choice for paragraphs.

**Comment by MaggieCabrera** [comment]
Let's close this since we swapped to using Inter instead
