### ISSUE TITLE
Optimize fonts

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentytwentyfour#177]
Font files are, a bit like images #44, a significant part of the data when a webpage is loaded. It is therefore important to optimize the font files. Currently, the files are in `ttf` format. Woff2 is a more modern web font format, which is smaller in size and has great browser support for modern browsers.

Further optimization might be possible if we can reduce the amount of characters contained in the font file (subsetting). [Transfonter](https://transfonter.org) is a great tool for this. Any advice if we can further reduce?

**Comment by huzaifaalmesbah** [comment]
Fixed #176
