### ISSUE TITLE
Pattern links to external websites

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/twentytwentyfour#196]
We are using Wordpress.org for links when we need them on patterns, and this will be adding these links to millions of websites without proper context once the theme is out in the world. @nilovelez suggested to use https://example.com/ instead. Let's discuss and only link to wordpress.org when it's contextually appropriate. Should we be using # instead?

**Comment by beafialho** [comment]
I agree with only linking to wordpress.org when it's appropriate and using # instead.

**Comment by richtabor** [comment]
> I agree with only linking to wordpress.org when it's appropriate and using # instead.

Same.
