### ISSUE TITLE
Update WordPress minimum required version to 6.4 (before releasing)

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwentyfour#197]
**Description**

This theme will be dependent on different types of functionalities that will be released with WordPress 6.4. Please [check this issue](https://github.com/WordPress/twentytwentyfour/issues/6) for more information.

The goal of this issue is to work as a reminder that we need to update the [minimum](https://github.com/WordPress/twentytwentyfour/issues/6) [required](https://github.com/WordPress/twentytwentyfour/blob/trunk/style.css#L7) version of WordPress to 6.4 before releasing.

**Comment by juanfra** [comment]
The changes must happen in the `style.css` file, where the theme data is managed.

**Comment by MaggieCabrera** [comment]
If we do this, the theme will not work until 6.4 is released, let's wait until we merge this change

**Comment by juanfra** [comment]
Absolutely 👌 

Yes, that's why the issue was created as a reminder to do it before releasing 6.4. Or at least once we have a 6.4 in the beta testing plugin, that contributors can use to work.

**Comment by carolinan** [comment]
Oh I see, I misunderstood this PR I thought it was for both files: https://github.com/WordPress/twentytwentyfour/pull/306

**Comment by juanfra** [comment]
No problem. I re-opened it so that we can keep track of it and update it when the time comes. Thanks, Carolina 🙌
