### ISSUE TITLE
Border radius applied to images rather than image block

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#199]
We have a number of images within the assets directory that are using hard-cropped border radii in the image, rather than applying the border radius from Global Styles. We should have all images bundled with 0 border radius, and apply a holistic (and user-customizable) global style for the image (and other related elements) border radius. 

<img width="1218" alt="CleanShot 2023-09-05 at 15 06 47" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/370678a7-45b6-421e-be5e-9990cd91e866">
<img width="685" alt="CleanShot 2023-09-05 at 15 08 13" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/950b8d59-e3b2-445e-9c30-ae23503a970e">

(and others).

**Comment by richtabor** [comment]
The current method also causes issues if you apply an aspect ratio.

**Comment by colorful-tones** [comment]
I would be happy to tackle this across all patterns/templates once we all agree on a solution. I've added an initial PR #219 with one solution, but open to any ideas. Thanks!

**Comment by richtabor** [comment]
All look good other than the services image; let's re-export that without the radii. 

<img width="929" alt="CleanShot 2023-09-07 at 16 03 05" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/c6edb136-b1bd-47d0-8ec6-7b025cc4d3be">

**Comment by colorful-tones** [comment]
> All look good other than the services image

Yeah, I noted that in #235:

> I found a few that had filters applied and I could not export them with edit access. We'll likely need to re-export all the images for https://github.com/WordPress/twentytwentyfour/issues/44 . So, I'm leaving it as is.

We need somebody with edit access to Figma to re-export that file with the black-and-white filter applied, but no border radius.

Or we can wait and have all images addressed in #44

**Comment by MaggieCabrera** [comment]
> We need somebody with edit access to Figma to re-export that file with the black-and-white filter applied, but no border radius.
> 

Why don't we use duotone here?

**Comment by colorful-tones** [comment]
#289 adds the duotone to the Services image.
