### ISSUE TITLE
Create a contributors file

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwentyfour#2]
I don’t think there’s a way to automate this task, since we want to track both code and discussion contributions, but let’s create a CONTRIBUTORS.md file and keep a rolling task to update it every week with all new contributors to the theme.

**Comment by jordesign** [comment]
Just opened a PR for this one...
https://github.com/WordPress/twentytwentyfour/pull/11

**Comment by jeffpaul** [comment]
@luminuu @jeffikus seems like this can be closed now that #11 is merged, yeah?  Though perhaps a tweak to the PR template to try and capture any folks who should be captured as a contributor to a specific PR could be worthwhile?

**Comment by luminuu** [comment]
I think we can keep this issue open as a reminder to do this on a regular basis.

**Comment by MaggieCabrera** [comment]
I'm thinking of triage as a way of contributing that is really hard to track. If someone is helping labeling issues and PRs but they are not commenting on any of them, I don't think we have an easy way to track their contribution, so I strongly suggest if we have those kinds of contributors that they speak up so we can give them props too

**Comment by huzaifaalmesbah** [comment]
Yes I agree with you @MaggieCabrera  I think so too.

**Comment by jeffpaul** [comment]
Note that #171 aims to help with ensuring we're properly gathering contributors with each PR.

**Comment by jeffikus** [comment]
@MaggieCabrera @luminuu we could keep this open and when it comes to triage, we could go through all the issues/PRs right at the end of dev cycle and add people that way perhaps?

**Comment by jeffikus** [comment]
We do have activity view but it doesn't cover every area of triage https://github.com/WordPress/twentytwentyfour/activity

**Comment by luminuu** [comment]
I've checked back the latest version of the contributors file with what I had when I initially checked the count at WCUS that was then announced by Matt, and I've got a couple more people than that are in the current file:

```
| @gpotter | @gpotter |
| @michaelshowes | |
| @lefty55104 | @pbwebd |
| @anphira | @anphira |
| @rebekahmarkowitz | |
| @suprsam | @suprsam |
| @damonsharp | @damonsharp |
```

Either because they only had created/discussed in issues or their PR hasn't been merged yet I guess.

**Comment by MaggieCabrera** [comment]
Let's add 

`| @colorful-tones | @colorful-tones | `

to the list too

**Comment by colorful-tones** [comment]
> Let's add 
> 
> 
> 
> `| @colorful-tones | @colorful-tones | `
> 
> 
> 
> to the list too

✅ done

**Comment by huzaifaalmesbah** [comment]
> I've checked back the latest version of the contributors file with what I had when I initially checked the count at WCUS that was then announced by Matt, and I've got a couple more people than that are in the current file:
> 
> ```
> | @gpotter | @gpotter |
> | @michaelshowes | |
> | @lefty55104 | @pbwebd |
> | @anphira | @anphira |
> | @rebekahmarkowitz | |
> | @suprsam | @suprsam |
> | @damonsharp | @damonsharp |
> ```
> 
> Either because they only had created/discussed in issues or their PR hasn't been merged yet I guess.

@MaggieCabrera @luminuu Do I add them to the list of contributors? #280

**Comment by MaggieCabrera** [comment]
> > I've checked back the latest version of the contributors file with what I had when I initially checked the count at WCUS that was then announced by Matt, and I've got a couple more people than that are in the current file:
> > ```
> > | @gpotter | @gpotter |
> > | @michaelshowes | |
> > | @lefty55104 | @pbwebd |
> > | @anphira | @anphira |
> > | @rebekahmarkowitz | |
> > | @suprsam | @suprsam |
> > | @damonsharp | @damonsharp |
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Either because they only had created/discussed in issues or their PR hasn't been merged yet I guess.
> 
> @MaggieCabrera @luminuu Do I add them to the list of contributors? #280

yes please

**Comment by MaggieCabrera** [comment]
Can we make another pass before Friday afternoon (UTC time) on the non-code contributions? I've seen a few that have not been added, if no one gets to it before then I'll have a look.

**Comment by luminuu** [comment]
I can do this

**Comment by luminuu** [comment]
Updated the file as of 16:50 today in #474
