### ISSUE TITLE
Add aspect ratio to images within patterns

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#200]
We should assign an aspect ratio to image blocks within patterns, so that when replaced the design's original layout is kept intact. 

Example: 

<img width="1808" alt="CleanShot 2023-09-05 at 15 09 45" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/c5152dca-9e23-46e7-b709-887136e0745b">

**Comment by colorful-tones** [comment]
This could likely overlap with #44

**Comment by richtabor** [comment]
This is within the patterns themselves; not the images. I'm fine with whatever aspect ratio they're exported with for the most part — I don't see us needing to change those further, unless we're going to consolidate image a bit more.

**Comment by colorful-tones** [comment]
> This is within the patterns themselves

Yep

> we're going to consolidate image a bit more.

Yes, this was what I was hinting towards.

**Comment by MaggieCabrera** [comment]
Is there any pattern that still needs this?

**Comment by richtabor** [comment]
I think just these two: 

- [ ] hero — https://github.com/WordPress/twentytwentyfour/blob/trunk/patterns/hero.php#L40
- [ ] project-description — https://github.com/WordPress/twentytwentyfour/blob/trunk/patterns/project-description.php#L33

**Comment by MaggieCabrera** [comment]
I'm not sure about the hero one. It's on the home page, and on install, if the user doesn't change it, it will look kind of bad

**Comment by richtabor** [comment]
> I'm not sure about the hero one. It's on the home page, and on install, if the user doesn't change it, it will look kind of bad

I'm not following the relevance? 

But anyhow, Gutenberg does not support wide/full images with aspect ratio—yet https://github.com/WordPress/gutenberg/issues/53652.

**Comment by MaggieCabrera** [comment]
> > I'm not sure about the hero one. It's on the home page, and on install, if the user doesn't change it, it will look kind of bad
> 
> I'm not following the relevance?
> 
> But anyhow, Gutenberg does not support wide/full images with aspect ratio—yet [WordPress/gutenberg#53652](https://github.com/WordPress/gutenberg/issues/53652).

Sorry! my brain wasn't working this morning and I was thinking this issue was about replacing images with placeholders... Please ignore my comment

**Comment by MaggieCabrera** [comment]
> I think just these two:
> 
>     * [ ]  hero — https://github.com/WordPress/twentytwentyfour/blob/trunk/patterns/hero.php#L40
> 
>     * [ ]  project-description — https://github.com/WordPress/twentytwentyfour/blob/trunk/patterns/project-description.php#L33

none of those work with the aspect ratios that we have in the editor, so I didn't want to make a custom one. I'm closing this one unless we think we should do so
