### ISSUE TITLE
Update patterns to remove font-family

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#202]
In the same vein as https://github.com/WordPress/twentytwentyfour/issues/201, we should almost never need to apply a font family within a pattern. The exception is when a heading appears like paragraph text, and vise-versa — but that should almost never happen. 

<img width="325" alt="CleanShot 2023-09-05 at 15 16 50" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/96baa728-444c-4178-afed-cecdfffc9bbe">

**Comment by pbking** [comment]
All of the existing patterns that leverage an alternative font family are doing so to achieve the design, where the design does not use the default (system) font.  I believe all of these should stay as designed.

The only exception to this is the 'testimonial' patterns which erroneously had the 'Inter' font family assigned.  The linked issue cleans that up.
