### ISSUE TITLE
Update patterns to use spacing presets, not arbitrary values

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#203]
We should use spacing presets nearly exclusively throughout the theme. Any arbitrary value should be replaced with the closest spacing preset. 

<img width="418" alt="CleanShot 2023-09-05 at 15 21 38" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/3a7f74cd-b2a1-48c0-ac3f-cf1c21a2a054">

**Comment by colorful-tones** [comment]
I'm working through an audit for this right now. I'll report back shortly.

**Comment by colorful-tones** [comment]
I've begun inspecting the patterns for spacing preset usage. I'm solely focusing on `margin`, `padding`, `top`, `bottom`, `right`, `left`, `blockGap` usage and **ignoring** the following:

- Typography stuff - should be handled in #201 
- `border` stuff - should be handled in #363
- Image block dimensions (`width`, `height`), which should be handled in either #44 and/or #200

✅  means they're using spacing presets
🚀  incoming PR for this #362
⚠️  needs addressing (ran out of time)

- ✅ `about-2.php`
- ✅ `about.php`
- ✅ `centered-statement.php`
- ✅ `clients.php`
- ✅ `columns.php`
- ✅ `cta.php`
- ✅ `faq.php`
- ✅ `feature-grid.php`
- ✅ `features-with-images.php`
- ✅ `footer-portfolio.php`
- ✅ `footer-writer.php`
- ✅ `footer.php`
- ✅ `hero.php`
- ✅ `hidden-404.php`
- 🚀 `hidden-comments.php`
- ✅ `hidden-full-screen-image.php`
- ✅ `hidden-hidden-intro-text-left.php`
- ✅ `hidden-no-results-content.php`
- ⚠️ ~~`hidden-sidebar-writer.php`~~ (no longer)
- ✅ `hidden-sidebar.php`
- ✅ `left-aligned-cta-image.php`
- ✅ `offset-grid-image-posts.php`
- ✅ `page-01-business-home.php`
- ✅ `page-02-business-about.php`
- ✅ `page-03-portfolio-overview.php`
- ✅ `page-04-newsletter-landing.php`
- ✅ `page-05-portfolio-home.php`
- ⚠️ ~~`posts.php`~~ `posts-featured.php`
- ⚠️ `pricing.php`
- ✅ `project-description.php`
- ✅ `project-details.php`
- ⚠️ `project-layout.php`
- ✅ `rsvp.php`
- ✅ `services-cta.php`
- ✅ `team.php`
- ✅ `template-home-portfolio.php`
- ⚠️ `testimonial.php`

**Comment by colorful-tones** [comment]
One thing to clarify here. In @richtabor screenshot for this issue there are lots of `0` values, like `padding-left: 0`. I think the zeroing is fine in this case, and it is only non-zero values, like `padding-left: 7vh` we’re worried about in replacing with variables.

**Comment by richtabor** [comment]
Yea, 0 is fine. Even some of the smaller values are ok (like between post meta; small areas). But the vast majority should be presets.
