### ISSUE TITLE
Testing needed: Changes to spacing in WordPress 6.4

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfour#241]
There are planned changes being made to the spacing of blocks that use flex or grid in WordPress 6.4.
The backport of the change has not been committed to WordPress core yet, so for now, the theme structure and patterns with nested blocks need to be tested with the latest version of Gutenberg active.

https://github.com/WordPress/gutenberg/pull/53259

**Comment by dhrumilkumbhani** [comment]
@carolinan 
Planned changes are in progress regarding the spacing of blocks that utilize flex or grid in WordPress 6.4. It's worth noting that the backport of this change has not yet been committed to the WordPress core. Therefore, at this moment, it's crucial to thoroughly test the theme structure and patterns involving nested blocks using the latest active version of Gutenberg and WordPress 6.4.

I have personally conducted tests, and I'm pleased to report that everything is functioning as expected for me.

**Comment by richtabor** [comment]
Yea I'm building with the latest version of Gutenberg on my end.
