### ISSUE TITLE
Quote default and plain variations are the same

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#257]
We need to implement the quote block's styling within global styles, also accounting for the variations. 

Current: 

<img width="1094" alt="CleanShot 2023-09-07 at 09 21 35" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/36e183da-85ad-4e31-8696-49fc67342f38">
<img width="1092" alt="CleanShot 2023-09-07 at 09 21 30" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/619be413-eaca-4e8c-92d3-78c0e9e4e13f">

Expected: 

I would say "the first one should be "Plain" and the white background quote should be "Default".
<img width="680" alt="CleanShot 2023-09-07 at 09 22 24" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/bb7bde39-7bfa-4715-87d8-b92926b104e2">

**Comment by colorful-tones** [comment]
@richtabor I'm going to take a pass at this right now...
