### ISSUE TITLE
Full width content in single posts is not full width in the view

### ISSUE THREAD

**Issue by jffng** [WordPress/twentytwentyfour#278]
**Description**
Full width content in single posts does not appear full width in the view.

**Step-by-step reproduction instructions**
Go to the post editor, add some full width content like a cover block. 

**Expected behavior**
The content to appear full width in the view.

**Screenshots**
Editor | Front-end
--- | ---
<img width="1616" alt="Screenshot 2023-09-07 at 3 45 55 PM" src="https://github.com/WordPress/twentytwentyfour/assets/5375500/f61a6047-c364-4c2f-a41a-843f02565d7f"> | <img width="1616" alt="Screenshot 2023-09-07 at 3 45 59 PM" src="https://github.com/WordPress/twentytwentyfour/assets/5375500/481b7fc6-1699-447d-9853-1ae9ffd20e3e">
 

**Environment info**

**Additional context**

Discovered reviewing #269

**Comment by richtabor** [comment]
@jffng Related to https://github.com/WordPress/twentytwentyfour/pull/277 in part—but for page templates—if you want to give it a review as well. :)

**Comment by jffng** [comment]
Actually I think this is fixed in trunk, the branch I was testing I think was out of date. Closing!
