### ISSUE TITLE
Upload patterns to the directory 

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/twentytwentyfour#299]
Let’s upload all patterns to the directory once the theme is ready to be released

**Comment by richtabor** [comment]
We should even include a couple within theme.json to load from the directory. That would help educate folks on this front.

**Comment by MaggieCabrera** [comment]
> We should even include a couple within theme.json to load from the directory. That would help educate folks on this front.

Which ones do you think are a good fit for that? the more simple ones that don't have images?

**Comment by richtabor** [comment]
It's fine if some do (we already include images on other curated patterns). We could even make slight variations of existing ones, like this RSVP one: https://github.com/WordPress/twentytwentyfour/pull/323#issuecomment-1715582259

**Comment by richtabor** [comment]
Or we could use the newly merged placeholder stuff!

**Comment by carolinan** [comment]
I tested the following, which worked:
Add the slug of the remote pattern in theme.json: `"patterns": [ "mixed-shape-gallery" ]`
Add the pattern to a template or pattern: `<!-- wp:pattern {"slug":"mixed-shape-gallery"} /-->`

**Comment by richtabor** [comment]
Nice, I say we put one (or pull a pattern we like from the directory) into the theme, at least via theme.json. Give folks a solid example of what's possible.

**Comment by kafleg** [comment]
Great idea.
