### ISSUE TITLE
Home pattern is no longer loading in the home.html template.

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfour#324]
**Description**

The home pattern, patterns/page-01-business-home.php is no longer loading in the site editor in the home.html template.
The site editor shows the header and footer but not the pattern in the middle.

**Step-by-step reproduction instructions**
Go to Appearance > Editor and see that the page content is not visible.

**Expected behavior**

For the content to be visible.

**Environment info**

6.4-alpha-56555

**Comment by carolinan** [comment]
Removing  `* Post Types: page` from the pattern makes the content visible again.

**Comment by MaggieCabrera** [comment]
@richtabor is this a bug in Gutenberg?

**Comment by richtabor** [comment]
Which template/settings? 

<img width="393" alt="CleanShot 2023-09-12 at 08 15 31" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/7bacb2d3-234c-4d48-9c6a-991870e1a10b">


> @richtabor is this a bug in Gutenberg?

There is [this issue](https://github.com/WordPress/gutenberg/issues/45859) I wrote up last year indication that page post type patterns are not available in the site editor. Probably the same deal, though a different angle.

**Comment by richtabor** [comment]
> Removing  * Post Types: page from the pattern makes the content visible again.

Downside to this is that the "page" pattern is available in posts. Maybe it's not a huge deal, but it's a sharp edge in the experience.

**Comment by MaggieCabrera** [comment]
Fixing on https://github.com/WordPress/twentytwentyfour/pull/370 unless we get a fix in GB soon

**Comment by scruffian** [comment]
Alternative fix here: https://github.com/WordPress/twentytwentyfour/pull/375
