### ISSUE TITLE
Strings that need to be translated to English

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/twentytwentyfour#333]
**Description**

**Patterns**

- Footer portfolio
- Centered Statement
- Heading on left (hidden, shows in Home portfolio template and pattern)

**Templates**

- Writer home

**Comment by beafialho** [comment]
Here are the patterns copy in English:

**Heading on left** 
> I’m Leia Acosta, a passionate photographer who finds inspiration in capturing the fleeting beauty of life.

**Footer portfolio**

> Keep up, get in touch.
> Contact Me
wordpress@wordpress.org
> Follow Me
Instagram / Facebook

**Centered Statement**
> Études is not confined to the past—we are passionate about the cutting-edge designs shaping our world today.

**Writer home**
> I write about finance, management and economics, my book “Money Studies” is out now.
> Navigating Volatile Markets in Uncertain Times
> Exploring the global impact of central bank policies
> For Beginners: How to Start Investing in the Stock Market
> About the author
> I’m Adele Diouf, and I’m driven by an insatiable curiosity to unravel the complex tapestry of finance and economics. Over the course of more than a decade, my journey through the maze of global markets, monetary policies, and economic trends has provided readers with the tools needed to navigate the dynamic landscape of finance.
> Latest Articles
> Useful Links
> Things that I find useful and wanted to share with you.
> Latest inflation report ↗
> Financial apps for families ↗
> In today's dynamic economic landscape, navigating volatile markets requires a strategic approach that combines vigilance and adaptability. With fluctuations becoming the norm, investors must resist knee-jerk reactions and instead take a long-term perspective.

<img width="872" alt="Captura de ecrã 2023-09-12, às 11 42 47" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/4c1b868f-a6a9-4b46-86da-6d4b3c38db6c">

**Comment by MaggieCabrera** [comment]
Thank you Bea, you rock

**Comment by carolinan** [comment]
The sidebar "About the author" section has already been changed to using the post author biography block.
