### ISSUE TITLE
Portfolio footer: make it wide instead of full width

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/twentytwentyfour#338]
<img width="1770" alt="Screenshot 2023-09-12 at 17 40 24" src="https://github.com/WordPress/twentytwentyfour/assets/3593343/181bf3d6-97d6-4e54-a1e9-c8d29bf4a066">

Let's make this footer pattern be wide width instead of full width

**Comment by jordesign** [comment]
PR up in https://github.com/WordPress/twentytwentyfour/pull/349

**Comment by jordesign** [comment]
This can be closed with #349  being merged now cc/ @MaggieCabrera
