### ISSUE TITLE
Document design tokens

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyfour#34]
In creating my first pattern from the Figma file, I encountered some decisions I wasn't sure how to approach:

- Font sizes in Figma that aren't in theme.json
- Default spacing units

We should document some of these tokens and how to use them when creating patterns.

**Comment by luminuu** [comment]
Another one:
- Fonts

**Comment by richtabor** [comment]
> Default spacing units

Proposal here for fluid spacing: https://github.com/WordPress/twentytwentyfour/pull/102. 

I'm thinking the `40` preset to be used as the standard padding around edges.

**Comment by colorful-tones** [comment]
It is currently quite challenging to try and build a pattern. We should try to streamline some of these tokens and make them readily available. I recommend we update the variables in the Figma file _and_ make some docs (markdown table in README at the very least) for contributors to grab and reference key tokens. I'm happy to help and will be at tomorrow's meeting. 😄

**Comment by richtabor** [comment]
> I recommend we update the variables in the Figma file. 

I've done that. What kind of table do you think we need? I think as long as you're using a spacing, color, font size preset, then you're sitting good.

**Comment by colorful-tones** [comment]
I think [#213](https://github.com/WordPress/twentytwentyfour/pull/213) was a step in the right direction, but we'll have to be mindful of keeping it up to date if anything changes.
