### ISSUE TITLE
Sidebar template part preview

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/twentytwentyfour#340]
Can we improve a bit the preview of this template part? Should we hide it?

<img width="436" alt="Screenshot 2023-09-12 at 17 47 59" src="https://github.com/WordPress/twentytwentyfour/assets/3593343/46806f3a-0475-4572-b527-863e9fbfa0e1">

**Comment by carolinan** [comment]
@richtabor would this be solved just by changing the viewport width parameter?

**Comment by beafialho** [comment]
The Sidebar isn't looking good. Some font sizes are off, separators too and the links shouldn't contain posts, but exemplificatory paragraphs. I made some adjustments:

Can we add `16px` border radius to the author avatar?

```
<!-- wp:group {"style":{"spacing":{"blockGap":"2.5rem"}},"layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch"}} -->
<div class="wp-block-group"><!-- wp:group {"layout":{"type":"constrained"}} -->
<div class="wp-block-group"><!-- wp:image {"id":22,"width":80,"height":80,"scale":"cover","sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full is-resized"><img src="http://localhost:8881/wp-content/themes/twentytwentyfour/assets/images/team-member-3.webp" alt="" class="wp-image-22" style="object-fit:cover;width:80px;height:80px" width="80" height="80"/></figure>
<!-- /wp:image -->

<!-- wp:heading {"fontSize":"large"} -->
<h2 class="wp-block-heading has-large-font-size">About the author</h2>
<!-- /wp:heading -->

<!-- wp:post-author-biography {"style":{"typography":{"fontSize":"0.9rem"}}} /--></div>
<!-- /wp:group -->

<!-- wp:separator {"opacity":"css","className":"has-text-color has-base-3-color has-alpha-channel-opacity has-custom-borders-background-color has-background is-style-wide"} -->
<hr class="wp-block-separator has-css-opacity has-text-color has-base-3-color has-alpha-channel-opacity has-custom-borders-background-color has-background is-style-wide"/>
<!-- /wp:separator -->

<!-- wp:heading {"fontSize":"large"} -->
<h2 class="wp-block-heading has-large-font-size">Latest Posts</h2>
<!-- /wp:heading -->

<!-- wp:query {"queryId":11,"query":{"perPage":3,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false}} -->
<div class="wp-block-query"><!-- wp:post-template -->
<!-- wp:group {"style":{"spacing":{"blockGap":"0.5rem"}},"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:post-title {"isLink":true,"style":{"typography":{"fontSize":"1.4rem","lineHeight":"1.3"}}} /-->

<!-- wp:group {"style":{"spacing":{"blockGap":"0.22em","margin":{"top":"0","bottom":"0"}},"layout":{"selfStretch":"fit","flexSize":null}},"layout":{"type":"flex","flexWrap":"wrap","verticalAlignment":"stretch","justifyContent":"left"}} -->
<div class="wp-block-group" style="margin-top:0;margin-bottom:0"><!-- wp:post-date {"format":"M j, Y","isLink":true,"style":{"layout":{"selfStretch":"fit","flexSize":null}}} /-->

<!-- wp:paragraph {"style":{"typography":{"fontSize":"0.8rem"}},"textColor":"contrast-2"} -->
<p class="has-contrast-2-color has-text-color" style="font-size:0.8rem">—<p class="has-base-2-color has-text-color has-link-color" style="font-size:0.8rem"></p></p>
<!-- /wp:paragraph -->

<!-- wp:post-author-name {"isLink":true} /-->

<!-- wp:post-terms {"term":"category","prefix":"in "} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group -->

<!-- wp:spacer {"height":"var:preset|spacing|10"} -->
<div style="height:var(--wp--preset--spacing--10)" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->
<!-- /wp:post-template --></div>
<!-- /wp:query -->

<!-- wp:separator {"opacity":"css","className":"has-text-color has-base-3-color has-alpha-channel-opacity has-custom-borders-background-color has-background is-style-wide"} -->
<hr class="wp-block-separator has-css-opacity has-text-color has-base-3-color has-alpha-channel-opacity has-custom-borders-background-color has-background is-style-wide"/>
<!-- /wp:separator -->

<!-- wp:group {"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:heading {"fontSize":"large"} -->
<h2 class="wp-block-heading has-large-font-size">Useful Links</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Links I find useful and would like to share with my followers.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->

<!-- wp:group {"style":{"spacing":{"blockGap":"0.5rem"}},"layout":{"type":"flex","orientation":"vertical"}} -->
<div class="wp-block-group"><!-- wp:paragraph -->
<p><a href="#">Latest inflation report ↗</a></p>
<!-- /wp:paragraph -->

<!-- wp:paragraph -->
<p><a href="#">Financial apps for families ↗</a></p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
```

**Comment by carolinan** [comment]
As with the example links in the footer, lists of links  that are grouped together need to be as accessible as possible and should not be paragraphs with line breaks.

**Comment by richtabor** [comment]
>  lists of links that are grouped together need to be as accessible as possible and should not be paragraphs with line breaks.

Also makes then easier to edit.

**Comment by MaggieCabrera** [comment]
> The Sidebar isn't looking good. Some font sizes are off, separators too and the links shouldn't contain posts, but exemplificatory paragraphs. I made some adjustments:
> 
> Can we add `16px` border radius to the author avatar?
> 
> ```
> 
> <div class="wp-block-group">
> <div class="wp-block-group">
> <figure class="wp-block-image size-full is-resized"><img src="http://localhost:8881/wp-content/themes/twentytwentyfour/assets/images/team-member-3.webp" alt="" class="wp-image-22" style="object-fit:cover;width:80px;height:80px" width="80" height="80"/></figure>
> 
> 
> 
> <h2 class="wp-block-heading has-large-font-size">About the author</h2>
> 
> 
> </div>
> 
> 
> 
> <hr class="wp-block-separator has-css-opacity has-text-color has-base-3-color has-alpha-channel-opacity has-custom-borders-background-color has-background is-style-wide"/>
> 
> 
> 
> <h2 class="wp-block-heading has-large-font-size">Latest Posts</h2>
> 
> 
> 
> <div class="wp-block-query">
> 
> <div class="wp-block-group">
> 
> 
> <div class="wp-block-group" style="margin-top:0;margin-bottom:0">
> 
> 
> <p class="has-contrast-2-color has-text-color" style="font-size:0.8rem">—<p class="has-base-2-color has-text-color has-link-color" style="font-size:0.8rem"></p></p>
> 
> 
> 
> 
> </div>
> </div>
> 
> 
> 
> <div style="height:var(--wp--preset--spacing--10)" aria-hidden="true" class="wp-block-spacer"></div>
> 
> </div>
> 
> 
> 
> <hr class="wp-block-separator has-css-opacity has-text-color has-base-3-color has-alpha-channel-opacity has-custom-borders-background-color has-background is-style-wide"/>
> 
> 
> 
> <div class="wp-block-group">
> <h2 class="wp-block-heading has-large-font-size">Useful Links</h2>
> 
> 
> 
> <p>Links I find useful and would like to share with my followers.</p>
> </div>
> 
> 
> 
> <div class="wp-block-group">
> <p><a href="#">Latest inflation report ↗</a></p>
> 
> 
> 
> <p><a href="#">Financial apps for families ↗</a></p>
> </div>
> </div>
> 
> ```

I actually made some changes to the sidebar in [this](https://github.com/WordPress/twentytwentyfour/pull/381) PR. Some of the font sizes being used in the sidebar are not consistent with the presets we were using, so I changed them up a bit. I will compare my changes to the markup you are providing and try to find some common ground between them

**Comment by richtabor** [comment]
Noting that this still looks broken, when viewing the sidebar within the site editor: 

<img width="1525" alt="CleanShot 2023-09-18 at 13 38 57" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/e1cd560e-65ee-457e-9a1c-07821f4afd4c">

**Comment by richtabor** [comment]
> Should we hide it?

We should not hide the template part. It should be used more generously throughout our patterns/templates rather. https://github.com/WordPress/twentytwentyfour/issues/408

**Comment by richtabor** [comment]
> @richtabor would this be solved just by changing the viewport width parameter?

No, template parts don't have viewport width support.

**Comment by carolinan** [comment]
A <del>hidden</del> pattern inside a part could.

**Comment by richtabor** [comment]
I tried that; didn't work. Was hoping it would too.
