### ISSUE TITLE
Style footnotes

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/twentytwentyfour#342]
I'm not sure what needs to be done, but let's make sure that footnotes look great in TT4:

<img width="581" alt="Screenshot 2023-09-12 at 18 07 25" src="https://github.com/WordPress/twentytwentyfour/assets/3593343/bcbd7910-2688-40b0-a30e-883aaea0d45a">

**Comment by colorful-tones** [comment]
Here is what the current experience looks like with the latest `trunk` of TT4.

![Screenshot 2023-09-12 at 6 29 58 PM](https://github.com/WordPress/twentytwentyfour/assets/405912/897564ee-7dff-401b-8014-724ba51d22fc)

Question / Clarification: in the Figma file the text is in French I believe and the way the footnotes in the Paragraph block are expressed are different then what I'm used to (English). I'm not sure if this needs to be, or can be accounted for in the theme?

Examples from Figma file:

1. `vigilance et adaptabilité1. `
2. `prendre des décisions éclairées2.`
3. `retrouver l'équilibre avec le temps3.`

At the very least, I think we just need to make the footnotes at the bottom small font size. Other than that, I'm not sure what else might need adjusting here. 🤔

**Comment by colorful-tones** [comment]
I added PR to make the font size small.

**Comment by MaggieCabrera** [comment]
Yes, I've not worked with footnotes yet, so I didn't know if any work at all was required, but I opened the issue just in case. I think your PR is what the theme needs, I'm happy it looks so good out of the box anyway
