### ISSUE TITLE
Home Testimonial Block Color Contrast Issue

### ISSUE THREAD

**Issue by suprsam** [WordPress/twentytwentyfour#35]
## Issue summary

Color contrast too low for job title and company name (p class=has-secondary-color has-text-color has-link-color) in the testimonial block. 

## Recommendation
<img width="299" alt="testimonial block contrast issue" src="https://github.com/WordPress/twentytwentyfour/assets/4268632/8aaad57f-3d73-466d-a08c-347a2c2d53d5">

The contrast ratio needs to be 7:1 for normal-sized text or 4.5:1 for large text.

You can check color contrast here: https://webaim.org/resources/contrastchecker/

## Specifications
Template File: Home
**WCAG Principle:** https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html
**WCAG SC:** E.G. 3.2.2 On Input

**Comment by melchoyce** [comment]
We could use...

The tag color (#F2F2F2)
<img width="1305" alt="image" src="https://github.com/WordPress/twentytwentyfour/assets/2846578/61634b10-78d2-4012-9ab5-5d4174bc1fed">

---

Green (#B1C5A4)
<img width="1300" alt="image" src="https://github.com/WordPress/twentytwentyfour/assets/2846578/9bc686c2-5b76-4780-8acc-6458ed923878">

---

Beige (#CFCABE)
<img width="1316" alt="image" src="https://github.com/WordPress/twentytwentyfour/assets/2846578/3f98831f-f85e-4144-b14c-6bd9ccaeb495">

---

Brown (#C2A990)
<img width="1311" alt="image" src="https://github.com/WordPress/twentytwentyfour/assets/2846578/e77b7e2a-7c66-4e64-85b2-09b56a341293">

**Comment by beafialho** [comment]
We can use `#A2A2A2`, which is Contrast/Three in the color palette.

**Comment by carolinan** [comment]
This has been fixed, closing as completed. ( Contrast Ratio: 7.57:1 )
