### ISSUE TITLE
Index templates

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/twentytwentyfour#351]
According to the figma, we have 3 different designs for Index/Archive pages. Let's follow the same structure as we did for the home pages to develop patterns for the portfolio/writer options of these templates. Part of these are also reused on the search template, let's make everything modular using patterns.

**Default Archive:**

![Archive Template](https://github.com/WordPress/twentytwentyfour/assets/3593343/a45bc854-012e-4ea0-bef3-ec304af63e13)

**Portfolio archive:**

![Portfolio Archive](https://github.com/WordPress/twentytwentyfour/assets/3593343/d198b4db-9045-48e6-a561-951e5c185711)

**Writing Archive:**

![Writing Archive](https://github.com/WordPress/twentytwentyfour/assets/3593343/bbecb93e-536e-4b90-b95d-98ff26330798)

**Comment by carolinan** [comment]
We need to be careful of the naming here:  Should we use the template hierarchy or not?
For example archive-portfolio would always be used for a post type called portfolio.

**Comment by MaggieCabrera** [comment]
> We need to be careful of the naming here: Should we use the template hierarchy or not? For example archive-portfolio would always be used for a post type called portfolio.

This is why we should make these into patterns and not templates. We have a flow now to replace archive.html into something else via the patterns that we have. Adding the template is confusing.

**Comment by carolinan** [comment]
I don't think it is possible to do a query variation where only posts with featured images are included, is it?
