### ISSUE TITLE
RTL support and review

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/twentytwentyfour#356]
Let's make time to review the whole theme using a RTL language to see that things are placed on the correct places. Particularly things like the markers and icons:

<img width="1025" alt="Screenshot 2023-09-13 at 17 47 32" src="https://github.com/WordPress/twentytwentyfour/assets/3593343/dca28939-cb9e-401d-928e-99765ec128b0">

**Comment by vraja-pro** [comment]
Tested list and details blocks with RTL (Hebrew), no issue detected.
![Screenshot 2023-10-04 at 14 43 11](https://github.com/WordPress/twentytwentyfour/assets/65466507/f57752b4-052c-4b11-bd91-cf2726b987fb)
@carolinan

**Comment by MaggieCabrera** [comment]
@vraja-pro thank you for testing!

**Comment by MaggieCabrera** [comment]
I think we can close this one, let's reopen if we find any issues!
