### ISSUE TITLE
Quote Block Border Issue when Plain Option Selected

### ISSUE THREAD

**Issue by shail-mehta** [WordPress/twentytwentyfour#360]
# **Quote Block is showing border When Plain Option is selected** 

In Current Situation If I select Default Option then its Showing Quote Without Border & If I select Plain Option then it showing border in left side , I think We need to add this in reverse order.
**When Plain Option is selected it should show without border & if default option is selected it should show with border.**

### **Current: When Plain Option Selected:**
![Plain-quote](https://github.com/WordPress/twentytwentyfour/assets/22027190/56a194c5-e947-4a85-b816-093a475f0335)

### **Current: When Default Option Selected:**
![default-quote](https://github.com/WordPress/twentytwentyfour/assets/22027190/2921470a-1954-4fb5-8a1a-5e8df723242c)

### **When Plain Option is selected then it should show without border:**
![plain-quote-without-border](https://github.com/WordPress/twentytwentyfour/assets/22027190/7b7a6368-da00-4fc9-8b0f-84708bb89327)

### **When Default Option is selected then it should show with border:**
![default-quote-with-border](https://github.com/WordPress/twentytwentyfour/assets/22027190/cd186e8d-d7f5-400f-bc33-04008e378e1e)

**Comment by shail-mehta** [comment]
**PR:** https://github.com/WordPress/twentytwentyfour/pull/361

**Comment by colorful-tones** [comment]
I believe this was the way it was planned, but would need @MaggieCabrera @luminuu feedback. Here is the original discussion: https://github.com/WordPress/twentytwentyfour/issues/257

**Comment by richtabor** [comment]
Yes, the "Plain" one is the one with a border. The more expressive one is default. I don't think we need to change this.

**Comment by shail-mehta** [comment]
Thanks @colorful-tones and @richtabor for Clarification.

In TT3 and TT2 quote blocks has border in default option and no border in plain option. 

Let's Wait for @MaggieCabrera and @luminuu Feedback.

**Comment by MaggieCabrera** [comment]
Yes, what @richtabor and @colorful-tones said is right

**Comment by luminuu** [comment]
I'm fine with leaving it as is, the one with the border being the Plain one.

**Comment by shail-mehta** [comment]
Thank you for feedback. I am closing this discussion
