### ISSUE TITLE
`border-radius` consistency across all patterns

### ISSUE THREAD

**Issue by colorful-tones** [WordPress/twentytwentyfour#363]
**Description**

It is recommended we set `settings.custom.border.radius` to control a consistent `border-radius` value throughout patterns. Right now, I'm seeing a lot of `"border":{"radius":"16px"}` in patterns. So, maybe we go with `16px`? Either way, it should reference a variable.

We could also consider utilizing an existing spacing preset. Like @richtabor did in [`c7f123d`](https://github.com/WordPress/twentytwentyfour/commit/c7f123dc9b2e0fda8fde5a7e82198e0ebf692ba7)

Also, someone should run through the `theme.json` and look to streamline values to variable.

Here is a list of affected patterns that would need to be updated:

- [ ] `centered-statement.php`
- [ ] `clients.php`
- [ ] `cta.php`
- [ ] `pricing.php`

Maybe `testimonial.php` as well? I'm seeing `"border":{"radius":"999px"}`

**Comment by richtabor** [comment]
> Right now, I'm seeing a lot of "border":{"radius":"16px"} in patterns.

If it's a block that does not support rounded, that's what's used. Perhaps we add block style variations for those few block, like image had "rounded"?

**Comment by MaggieCabrera** [comment]
> > Right now, I'm seeing a lot of "border":{"radius":"16px"} in patterns.
> 
> If it's a block that does not support rounded, that's what's used. Perhaps we add block style variations for those few block, like image had "rounded"?

I think that makes it more consistent, yes

**Comment by MaggieCabrera** [comment]
We changed this so we are using a preset variable so I'm closing this one
