### ISSUE TITLE
Ensure all assets have proper credits/licensing information

### ISSUE THREAD

**Issue by sabernhardt** [WordPress/twentytwentyfour#364]
Ideally before merging into Core:

1. Check the sources of all bundled fonts and images.
2. Add credits to the readme.txt.
3. Add any necessary license.txt files.

**Comment by sabernhardt** [comment]
Right now, none of the images have credits in the readme.

The Cardo font has credit and licensing information, with a link to the license. Should it have a copy of the license document too?

**Comment by MaggieCabrera** [comment]
Thank you for logging this issue, it's part of the pre launch tasks. I checked TT3 and it's [including the license](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-content/themes/twentytwentythree/assets/fonts/dm-sans/LICENSE.txt) files inside the assets folders, so I'm happy to go with that.

TT2 does [this](https://github.com/WordPress/wordpress-develop/blob/11c53d559bf89c4647f75ca464886d592c0c1fb1/src/wp-content/themes/twentytwentytwo/readme.txt#L89) about the images. There's still some potential changes coming to the images if we remove some to use placeholders instead, but it's unlikely that we will be adding more, so this is a task we could start working on. @beafialho, can you tell us where to find the info for the image licensing? If you download a zip with the theme you can check the images being used inside the assets folder, we only need info for those

**Comment by beafialho** [comment]
Here are the image sources for the images in the assets folder:

**about.webp** - https://www.rawpixel.com/image/3297419/free-photo-image-interior-hallway-architecture
**business-app.webp** - https://www.rawpixel.com/image/5928004/photo-image-public-domain-hand-person
**business-hero.webp** - https://www.rawpixel.com/image/430335/free-photo-image-architecture-building-roof
**home.webp** - https://www.rawpixel.com/image/3286615/free-photo-image-texture-architecture-building
**left-aligned-cta.webp** - https://www.rawpixel.com/image/3283970/free-photo-image-pattern-artwork-abstract
**project-1.webp** - https://www.rawpixel.com/image/3289063/free-photo-image-architectural-detail-architecture
**project-2.webp** - https://www.rawpixel.com/image/430585/free-photo-image-stairs-staircase-concrete
**project-overview.webp** - https://www.rawpixel.com/image/3286187/free-photo-image-person-stairs-architecture
**rsvp.webp** - https://www.rawpixel.com/image/430558/free-photo-image-abstract-architecture-art-public-domain
**services.webp** - https://www.rawpixel.com/image/5928302/photo-image-public-domain-person-construction
**team-member-1.webp** - https://stocksnap.io/photo/girl-woman-IMGDU7F1X9
**team-member-2.webp** - https://stocksnap.io/photo/business-people-SMJLMCZMTN
**team-member-3.webp** - https://stocksnap.io/photo/people-woman-MU7G67710S
**team-member-4.webp** - https://stocksnap.io/photo/people-man-6LPO676JKO
**testimonial-avatar.webp** - https://stocksnap.io/photo/woman-working-KFOCL5M9AN
**tt4_projectoverview.jpg** - https://www.rawpixel.com/image/3286725/free-photo-image-black-and-white-background-photos
**writer-avatar.webp** - https://nappy.co/photo/3565

**Comment by carolinan** [comment]
Images from nappy.co are not GPL compatible. They claim to use CC0, but adds limitations that are not GPL compatible here: https://nappy.co/license

It is fine to use in a demo. it is a non issue for the theme since this image will be replaced by the user avatar.

**Comment by carolinan** [comment]
Looks like the latest bundled themes do not have their own GPL license **file**. I suppose it is covered by https://core.trac.wordpress.org/browser/trunk/src/license.txt?rev=56642
