### ISSUE TITLE
Add translation strings to "columns" pattern

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwentyfour#37]
Translation strings need to be added to the columns pattern. For example:

**Before**
`<li>Showcase your projects</li> `

**After**
`<li><?php echo esc_html__( 'Showcase your projects', 'twentytwentyfour' ); ?> </li>`

**Comment by damonsharp** [comment]
PR opened for this [here](https://github.com/WordPress/twentytwentyfour/pull/55)
