### ISSUE TITLE
Document how to change from one use case (one design) to another

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfour#376]
**Is your feature request related to a problem? Please describe.**

Document step by step ( click by click ) how to change from the default design to "writer" or "portfolio".

**Comment by MaggieCabrera** [comment]
I asked for a video for this. Where should we document this change better? 


https://github.com/WordPress/twentytwentyfour/assets/3593343/bc21d8e5-1eb0-4cb4-a31f-bddf1cb36b29
