### ISSUE TITLE
Default Footer: Column titles using wrong font

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfour#388]
Notice the text "About", "Privacy" and "Social Media". Those headings also should be at the same horizontal level as the logo.

| Current      | Figma Design |
| ----------- | ----------- |
|   <img width="1441" alt="Captura de ecrã 2023-09-17, às 11 50 29" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/a147f791-75a0-4849-94ba-0fe947c937a0">      |     <img width="1759" alt="Captura de ecrã 2023-09-17, às 11 57 15" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/60fca644-12ba-4ed7-ad74-e25de936b7d3">    |

**Comment by jordesign** [comment]
Opened a PR for this in #394
