### ISSUE TITLE
Improve search form appearance

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfour#389]
Unfortunately there's no UI to perfect these forms accurately but can we improve this? It's looking very unpolished. The placeholder font weight should be **Regular** and the input field border radius should be the same as the theme's buttons.

These details make a difference.

| Reality      | Expectation |
| ----------- | ----------- |
| <img width="687" alt="Captura de ecrã 2023-09-17, às 12 37 57" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/dd2f56f8-4846-4d33-9a04-57b285a5e937">   |  <img width="1189" alt="Captura de ecrã 2023-09-17, às 12 41 24" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/e25332c7-bda0-4950-9467-f7dace581f98">    |

**Comment by hanneslsm** [comment]
Changing the border radius of the input field is currently not possible: https://github.com/WordPress/gutenberg/issues/51617 (on a global level)

**Comment by carolinan** [comment]
Should all text input elements, like in the log in or comments, have the same radius?

**Comment by carolinan** [comment]
Should only the placeholder text be regular, or also the text that the user enters into the field on the front?

**Comment by beafialho** [comment]
> Should all text input elements, like in the log in or comments, have the same radius?

All text inputs should ideally have the same radius, yes.

> Should only the placeholder text be regular, or also the text that the user enters into the field on the front?

The placeholder and the text users enter should both be Regular.

**Comment by carolinan** [comment]
Ouch the form for the login/out block is especially bad. I did not know that this button is missing the CSS class that styles the buttons.

Found an issue for it: https://github.com/WordPress/gutenberg/issues/50466

![form blocks](https://github.com/WordPress/twentytwentyfour/assets/7422055/56634ef3-f0cb-442d-b708-cfe7c5ff2b90)

**Comment by carolinan** [comment]
Aha: https://github.com/WordPress/gutenberg/issues/50466

**Comment by beafialho** [comment]
Can all input fields have the same border radius as the search?

**Comment by carolinan** [comment]
I added a screenshot here: https://github.com/WordPress/twentytwentyfour/pull/398

**Comment by beafialho** [comment]
Great, thank you!
