### ISSUE TITLE
Sidebar: Latest Post > Post Meta wraps unusually with longer strings

### ISSUE THREAD

**Issue by jordesign** [WordPress/twentytwentyfour#397]
**Description**

The post meta of posts in the sidebar template part look great when the category and author names are short. However, if either of those are longer strings - each post meta element wraps which ends up looking bad.

Figma:

<img width="308" alt="Screenshot 2023-09-18 at 2 24 05 pm" src="https://github.com/WordPress/twentytwentyfour/assets/1842363/f959c149-4027-49a1-b397-33b3a59b941a">

Actual:
<img width="307" alt="Screenshot 2023-09-18 at 2 23 35 pm" src="https://github.com/WordPress/twentytwentyfour/assets/1842363/f3edf8f2-bcca-4372-89f8-7f096c678b1e">

**Step-by-step reproduction instructions**
1. Use an author display name with longer strings and multiple words
2. Add a category to a recent post which is longer and/or contains multiple words
3. View a template which includes the sidebar (like single-sidebar.html).

**Comment by jordesign** [comment]
The font-size in figma is definitely smaller (14px) but it is the handling of the divs inside the row which is also causing the misalignment when things wrap...

It would amazing if we could get those strings to just run inline...

**Comment by MaggieCabrera** [comment]
Can you test with [this PR](https://github.com/WordPress/twentytwentyfour/pull/381)? How much is still relevant?

**Comment by jordesign** [comment]
Brilliant - it looks great with that PR - this one's no longer needed.
