### ISSUE TITLE
Set up 2024.wordpress.net

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwentyfour#4]
We should set up a development site + a github action that deploys trunk of this theme.

For reference, here's the same discussion for Twenty Twenty-Two: https://github.com/WordPress/twentytwentytwo/issues/21

**Comment by mikachan** [comment]
@kraftbj helped with the Twenty Twenty-Three demo site, so just dropping a ping here 🙇  https://github.com/WordPress/twentytwentythree/issues/5

**Comment by kraftbj** [comment]
Thanks for the ping. I'll jump on it!

**Comment by kraftbj** [comment]
I have the site generated with Akismet, Gutenberg + 2024 active. It's set to update every couple minutes with a git pull off of this repo. Both themes are set to autoupdate as well.

Who all should get access to modify the content? You can send me e-mail addresses via Core Slack to me.

As in the past, individuals had logins but could reassign content to a default user.

**Comment by kraftbj** [comment]
Reached out to the folks mentioned in https://github.com/WordPress/twentytwentyfour/issues/44#issuecomment-1704980752 via Slack DM to confirm details.

**Comment by kraftbj** [comment]
Added @MaggieCabrera @beafialho @luminuu to the demo site. As far as I'm aware, there are no pending tasks for me until the site is ready to into long-term self-updating mode. If y'all want to keep this issue open to track adding any content, go for it. Otherwise, feel free to close!

**Comment by MaggieCabrera** [comment]
Yes, we'll keep the issue to add content, thank you for your help @kraftbj !

**Comment by MaggieCabrera** [comment]
I took a pass at this and added Pages for

- [Business About page](http://2024.wordpress.net/index.php/about/)
- [Portfolio page](http://2024.wordpress.net/index.php/portfolio/)
- [Newsletter landing page](http://2024.wordpress.net/index.php/newsletter-landing/)
- [Page](http://2024.wordpress.net/index.php/patterns/) for the rest of the patterns not present in one of the previous ones

**Comment by MaggieCabrera** [comment]
@beafialho would you please create posts so that the patterns using the query loop show some content? Maybe we could create different post types so we can show different posts on the query blocks based on if the page is portfolio, business or writer

**Comment by beafialho** [comment]
Thanks for adding those pages @MaggieCabrera, yes I can add the posts.

**Comment by colorful-tones** [comment]
I just wanted to note that the ‘Photograper Demo’ in the main nav points to this odd URL `https://tt4portfolio.mystagingwebsite.com/`

![image](https://github.com/WordPress/twentytwentyfour/assets/405912/c43b9539-2df2-4307-a095-0b34904c5b8b)

**Comment by MaggieCabrera** [comment]
Thanks, I made pages with the patterns for those two. The pattern for the blogger one is still not merged so it doesn't work. We need to add more posts for the photographer site to look good

**Comment by MaggieCabrera** [comment]
@beafialho I did the following for the demo site:

I installed a plugin that adds custom post types and created the writer/portfolio ones. This makes it so we can set our query blocks to show only posts of that custom post type. I set the photographer page to do just that. So now you only have to create the posts specific to writer/portfolio in the specific post types:

<img width="918" alt="Screenshot 2023-09-15 at 18 20 23" src="https://github.com/WordPress/twentytwentyfour/assets/3593343/52beeabf-8f33-44fb-a014-0b370db0ffe1">

**Comment by beafialho** [comment]
@MaggieCabrera I was editing the demo site and some questions came up:

1. When I create a new post under Writer or Portfolio Items, I can't add tags, categories or assign a post author, is that that can be set up in the plugin?
2. I've added all posts to the [Writer](http://2024.wordpress.net/index.php/blogger-demo/) and [Portfolio](http://2024.wordpress.net/index.php/photographer-demo/), but somehow they're not showing up correctly. Is that something that is yet to be set up in the indexes?

**Comment by MaggieCabrera** [comment]
> @MaggieCabrera I was editing the demo site and some questions came up:
> 
>     1. When I create a new post under Writer or Portfolio Items, I can't add tags, categories or assign a post author, is that that can be set up in the plugin?
> 

Yes, and I can allow for it

>     2. I've added all posts to the [Writer](http://2024.wordpress.net/index.php/blogger-demo/) and [Portfolio](http://2024.wordpress.net/index.php/photographer-demo/), but somehow they're not showing up correctly. Is that something that is yet to be set up in the indexes?

I'll check, thank you

**Comment by MaggieCabrera** [comment]
I think I fixed everything, let me know if there's anything else!

**Comment by beafialho** [comment]
It's all working now, thank you!

**Comment by carolinan** [comment]
I noticed that the image here is broken: http://2024.wordpress.net/index.php/rsvp/

**Comment by beafialho** [comment]
That image comes from the pattern. Or should we replace it manually?

**Comment by carolinan** [comment]
It should work with just the pattern. I wonder if the image did not get uploaded, or if the path in the pattern is wrong.

**Comment by MaggieCabrera** [comment]
I updated the broken patterns (they were using the old names, and that's why they weren't loading). I think we can close this one
