### ISSUE TITLE
Audit block locking

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfour#400]
**Description**
Some blocks have `lock":{"move":false,"remove":false}` which doesn't do anything.
This can be removed. The post content blocks should probably stay locked (remove: true) though.

**Comment by carolinan** [comment]
I am finding that there are still post content blocks that have no locking, is that intentional?

**Comment by MaggieCabrera** [comment]
> I am finding that there are still post content blocks that have no locking, is that intentional?

Probably an oversight, let's reopen
