### ISSUE TITLE
Sidebar should be referenced as template part, not the hidden pattern

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#408]
If the sidebar referenced is the `sidebar` template part, then it can be reused throughout templates. Otherwise it's just content that you may have to change every time you add a starter pattern with a sidebar. 

We should make sure all templates/patterns leverage the sidebar template part. 

<img width="480" alt="CleanShot 2023-09-18 at 13 29 29" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/50fcb5e9-a663-485a-904f-3c8e8d43a567">

**Comment by MaggieCabrera** [comment]
This has been solved
