### ISSUE TITLE
Post meta should be referenced as template part, not the hidden pattern

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#409]
If the post meta display was using a template part, then it can be reused throughout templates — and edited from one source. Otherwise, you'd have to make a post meta change to every template. 

I propose we make a template part for the post meta, then use that throughout, instead of referencing the pattern directly.

<img width="453" alt="CleanShot 2023-09-18 at 13 35 54" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/baf4877a-1449-401a-9797-700c809e264c">

**Comment by MaggieCabrera** [comment]
Mmmh, the reason why we hide templates like this one and the comments one is mainly for dev convenience, so we avoid code duplication. If you think this is not adding noise to the list of template parts, I'm ok with doing this if you think it brings value to the user too

**Comment by richtabor** [comment]
It's also for user convenience to not have to edit it in multiple places I'd say :)

**Comment by MaggieCabrera** [comment]
> It's also for user convenience to not have to edit it in multiple places I'd say :)

yeah, I think that's valid, I'm happy with changing to a template part. Would you do the same for the comments pattern?

**Comment by richtabor** [comment]
> Would you do the same for the comments pattern?

Is it used in more than one place, page and post? If so, then yea.
