### ISSUE TITLE
Remove Page Writer template

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#412]
It's so close to the existing "Page" template, as the only change is the text alignment. 

I propose we remove this custom template and consolidate. It could be a pattern template, but it doesn't really need to be with such a small change. 

Removing this will reduce the noise in the site editor > templates view.

<img width="1316" alt="CleanShot 2023-09-18 at 15 19 21" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/53f53997-9bc6-4be9-9e5c-383132270a5d">
<img width="1321" alt="CleanShot 2023-09-18 at 15 19 13" src="https://github.com/WordPress/twentytwentyfour/assets/1813435/02274fb2-9973-4f70-99c0-61f5135e47d5">

**Comment by MaggieCabrera** [comment]
I think this can be removed, and we can make the adjustment on the demo site if need be
