### ISSUE TITLE
Style Variation: Sandstorm

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfour#420]
<img width="873" alt="Captura de ecrã 2023-09-19, às 11 59 39" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/7953d662-80a9-407f-acea-9222653f88f7">
<img width="872" alt="Captura de ecrã 2023-09-19, às 11 59 32" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/da608834-1391-490d-bea6-1cd58494e02a">

[sandstorm.json.zip](https://github.com/WordPress/twentytwentyfour/files/12659019/sandstorm.json.zip)

**Comment by MaggieCabrera** [comment]
We have a problem with the fonts in that if we have style variations that use the same font for heading and body they will show duplicated on the font families dropdown :( We decided to go around that by using Inter for the headings and the system font for the body on the sans-serif variations that you designed (discussed in https://github.com/WordPress/twentytwentyfour/pull/367#issuecomment-1721272112)

**Comment by beafialho** [comment]
Oh, that's weird... This variation uses **Instrument Sans** though.

**Comment by MaggieCabrera** [comment]
> Oh, that's weird... This variation uses **Instrument Sans** though.

I know, but the result of having it apply to both body and headings will end up with two instances of Instrument sans, one for each of them

**Comment by beafialho** [comment]
So, we can't have a variation with just one font? Why is it a problem that it shows duplicated?

**Comment by MaggieCabrera** [comment]
> So, we can't have a variation with just one font? Why is it a problem that it shows duplicated?

just that it's confusing for the user, and also because we are enqueing the font twice, which is not great but also not terrible. @richtabor what do you think?

**Comment by richtabor** [comment]
Yea it’s a strange edge case we’re hitting. Perhaps we should open an issue to never duplicate fonts. I don’t expect it for 6.4, but would be good anyhow. 

Could we use inter for body font here as well?

**Comment by beafialho** [comment]
Let me rethink the variations. I'd love to use some different fonts.

**Comment by beafialho** [comment]
Ok I think I found a nice solution for this one, using Instrument Sans for paragraphs and Jost for headings. Updated file here:

[sandstorm-2.json.zip](https://github.com/WordPress/twentytwentyfour/files/12674152/sandstorm-2.json.zip)

<img width="1046" alt="Captura de ecrã 2023-09-20, às 14 51 57" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/d3361cd0-387a-46f1-9f6c-ff34c60d1259">

**Comment by MaggieCabrera** [comment]
@beafialho that variation includes a lot of files for the fonts, do we need them all? we are only using 3 for Cardo on the main style.

**Comment by richtabor** [comment]
@beafialho If you want to reduce, we can just change heading font and not body. I've proposed it top-level here so we can use it in variations easily if wanted: https://github.com/WordPress/twentytwentyfour/pull/452.

**Comment by richtabor** [comment]
> that variation includes a lot of files for the fonts

It may be best to lean on [variable fonts](https://fonts.google.com/?vfonly=true) only.

**Comment by beafialho** [comment]
> @beafialho that variation includes a lot of files for the fonts, do we need them all?

No, we only need Instrument Sans and Jost here. Is it possible to use my file, just for the sake of the font sizes I set?

**Comment by MaggieCabrera** [comment]
What I meant is we are adding too many weights for the fonts

**Comment by beafialho** [comment]
Oh, variable works too if it's better due to size. Through the Create Block Plugin I just selected the fonts from the Google fonts dropdown, but I can send you the variable ones if you'd like.

**Comment by MaggieCabrera** [comment]
That helps, thank you.

**Comment by beafialho** [comment]
Here they are:

[Instrument_Sans.zip](https://github.com/WordPress/twentytwentyfour/files/12682337/Instrument_Sans.zip)
[Jost.zip](https://github.com/WordPress/twentytwentyfour/files/12682338/Jost.zip)
