### ISSUE TITLE
Single post: Content reaches the edge of the browser on small widths

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfour#421]
**Description**
In single posts, the content reaches the edge of the browser. Even content that is not set to full width itself.
The content starts moving closer to the edge at ca 740px.

**Expected behavior**
I expect there to be spacing between the content and the edge of the browser, unless the individual block inside the post content is set to full width.

**Screenshots**
![Content positioning on small screen](https://github.com/WordPress/twentytwentyfour/assets/7422055/47afd479-9849-43e2-b470-ab880b1aa47c)

**Environment info**

 - Device: Desktop
 - OS: macOS
 - Browser: Chrome
 - Version:  117.0.5938.88 
 
 6.4 current trunk, Gutenberg current trunk

**Comment by MaggieCabrera** [comment]
I don't see if this is a regression or if it's an older bug. Let's make sure when we fix this that we are still capable of adding full and wide with blocks to the post content on desktop

**Comment by beafialho** [comment]
This is also happening in this pattern (at least in the demo site):

<img width="572" alt="Captura de ecrã 2023-09-25, às 10 23 03" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/973d7c57-4317-4ef1-a5bd-d3b7151821c8">

**Comment by carolinan** [comment]
But it doesn't happen on default pages, maybe the code can be compared and copied from them.

**Comment by benharri** [comment]
temporary workaround is to manually set the width on the post content block
