### ISSUE TITLE
Team pattern: Minor adjustment

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfour#423]
Two of the names of the team members are not in **Bold**, they should be for consistency.

<img width="1394" alt="Captura de ecrã 2023-09-19, às 15 41 46" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/d014010e-5bea-4e76-9111-f83313695b26">

**Comment by shail-mehta** [comment]
PR : https://github.com/WordPress/twentytwentyfour/pull/424
