### ISSUE TITLE
Quote (Plain): Improve appearance

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfour#439]
Currently the Plain Quote is looking a bit awkward. Let's improve its appearance by setting it to use `System font Semi Bold` only for the quote, citation should remain `Regular`. The line height should be `1,6`. Alternatively, see [Figma](https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=565-9983&mode=design&t=mlxcmncwpkBhDVAw-4).

| Currently      | Intended |
| ----------- | ----------- |
|  <img width="769" alt="Captura de ecrã 2023-09-20, às 12 04 18" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/06c5a85c-58b2-4f09-9ce2-77623e54248b">    |   <img width="848" alt="Captura de ecrã 2023-09-20, às 12 06 32" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/ddd494a1-e869-4f20-8821-710f7b0f2219">   |

This one seems to look the best default for the quote in a paragraph. If we want to just create a post that's a quote though, like the example below, is it possible to make the larger one default for such cases?

<img width="1589" alt="Captura de ecrã 2023-09-20, às 12 22 40" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/6f6c8909-0f96-440b-9f60-0c401201f463">

**Comment by richtabor** [comment]
We can only have one default style. Currently it’s the bigger one, while “Plain” is the style with the border to the left.  I think it’s fine to keep the default as it is today. 

“Plain” comes from Gutenberg.

**Comment by beafialho** [comment]
In your opinion, what should be the default?

**Comment by richtabor** [comment]
I think the white one. The border one looks more "plain", which is the style name we have to use.

**Comment by beafialho** [comment]
Ok, in any case, I suggest we improve the Plain one's appearance.

**Comment by luminuu** [comment]
@beafialho Do you want to provide us some design that we can implement for the plain quote variant?

**Comment by beafialho** [comment]
@luminuu it's in the screenshot above in the "Intended" column. Also [here](https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=565-9983&mode=design&t=cqqqMMwPUdJFi9iN-4) on Figma.

**Comment by MaggieCabrera** [comment]
I'm working on this and just the border requires an impressive amount of CSS to make it work on the three alignments plus RTL. We can do that, but it feels a little overkill to me
