### ISSUE TITLE
Optimize images

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/twentytwentyfour#44]
The images are too big and they need optimizing

**Comment by LittleBigThing** [comment]
+1

Also, there are a couple of questions worth asking with regard to images:

- [x] Should the images be bundled with the theme? They make a significant amount of data that might not be worth distributing with each WordPress download. Also, they won't be used in the final websites. <strike>Could they be linked from Openverse?</strike>
- [x] Since WordPress supports WebP, shouldn’t we use this format (if the images are bundled)?
- [ ] Can we review the actual size that are needed for the proposed design (if bundled)? I think we can decrease the sizes significantly for some (width x height).
- [x] Should we bundle this many images? Could we use the same image instead repeatedly for some designs?
- [x] Could we use placeholders for some patterns? They are much smaller in size... the images will be swapped for 99.9% of the websites. Placeholders might even make it clearer that one can swap the image.

**Comment by carolinan** [comment]
No, loading remote resources is not allowed for themes in the theme directory.

**Comment by MaggieCabrera** [comment]
We might end up removing many of them, I ported every image from the original demo site Bea used to work on the design but if they are not used on the patterns they will be removed

**Comment by beafialho** [comment]
How can I help here? I can export the images if that's helpful. 

Is there a best practice to how they should be named? What's the image format we want to use?

**Comment by MaggieCabrera** [comment]
> How can I help here? I can export the images if that's helpful.
> 
> Is there a best practice to how they should be named? What's the image format we want to use?

I think we can wait until all patterns are done and then make a pass to remove the ones we are not using. I think many of them are only used in the demo posts and shouldn't live in the theme. Also, those demo posts should probably be replicated in 2024.wordpress.net. @kraftbj can you give access to @beafialho @luminuu and me? Thank you!

**Comment by beafialho** [comment]
I can populate the demo site once it's appropriate.

It would be great to have 3 distinct demo sites for Twenty Twenty Four, to showcase the three use cases shown in the design concept, how do you suggest doing that?

**Comment by MaggieCabrera** [comment]
> I can populate the demo site once it's appropriate.
> 
> It would be great to have 3 distinct demo sites for Twenty Twenty Four, to showcase the three use cases shown in the design concept, how do you suggest doing that?

Can we make it in one and have separate pages for each of the homes and put them in the nav menu?

**Comment by beafialho** [comment]
That way we can't show the different footers and the three use cases don't get showcased as immersively, in different languages, background colors, etc

**Comment by MaggieCabrera** [comment]
> That way we can't show the different footers and the three use cases don't get showcased as immersively, in different languages, background colors, etc

actually we might be able to if we create a blank template, I will give it a try and let you know

**Comment by LittleBigThing** [comment]
Have we decided about which image format we will use? Is there a reason not to use WebP?

The patterns are now being created with JPGs.
This is relevant for the demo site as well.

**Comment by MaggieCabrera** [comment]
@mikachan what are your thoughts on this?

**Comment by colorful-tones** [comment]
I think it would be nice to lean into aspect ratio (see #200) and limit the theme to a handful of images only (maybe 6-10). Make sure they're optimized. I think `.webP` would be fine. Also, they should all likely utilize the `is-style-rounded` variation for Image block, which would be established in #235

**Comment by huzaifaalmesbah** [comment]
This is not a good preview. How can we improve it?
<img width="373" alt="Screenshot 2023-09-07 at 1 44 33 AM" src="https://github.com/WordPress/twentytwentyfour/assets/63150399/d0c315d7-9ca6-4759-8296-d977373687ff">

**Comment by mikachan** [comment]
👋 I vote for using WebP in as many cases as possible. If for whatever reason WebP doesn't work nicely with certain images, it'd be great to compress and optimise them as much as reasonably possible.

**Comment by kraftbj** [comment]
Just saw the request to add folks to 2024.wordpress.net. I'll reach out to y'all after my (U.S. time) morning meetings.
