### ISSUE TITLE
Portfolio Post Template: Misplaced post meta

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfour#440]
The post meta is currently misplaced in the template. It should align to the left wide width.

| Currently      | Figma |
| ----------- | ----------- |
|  <img width="1442" alt="Captura de ecrã 2023-09-20, às 12 28 25" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/09ffba16-8dd8-4cad-9d42-4c2bba7a9746">    |    <img width="875" alt="Captura de ecrã 2023-09-20, às 12 29 01" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/2df01d38-5979-4069-b4c2-075f6c95d43f">  |

**Comment by carolinan** [comment]
How did you test this? I am getting "Template part has been deleted or is unavailable: post-meta"

**Comment by MaggieCabrera** [comment]
It shows on http://2024.wordpress.net/index.php/portfolio/bike-in-colorful-wall/

**Comment by carolinan** [comment]
Solved in https://github.com/WordPress/twentytwentyfour/pull/463
