### ISSUE TITLE
Check if images need alt text

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwentyfour#445]
Various images are used in the theme and need to have an alternative text added.

Some images are only decorative, so these do not need an alternative text added, so screen readers can ignore them.

**Comment by shail-mehta** [comment]
PR: https://github.com/WordPress/twentytwentyfour/pull/446

**Comment by shail-mehta** [comment]
@luminuu  I have added new pr for project layout pattern (Reverted footer-portfolio alt text & changed project-layout.php image alt text)

In last PR there are conflicts so created new PR https://github.com/WordPress/twentytwentyfour/pull/451

**Comment by luminuu** [comment]
@shail-mehta Please see the suggestions Maggie has made in the PR and update it.
