### ISSUE TITLE
Audit template parts to only use `header` and `footer` in templates/patterns

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#454]
Ensure we're using the `header` template part everywhere, and `footer` template part as well. Not any of the alternatives. 

As noted in #411, 

> TT4 also has multiple header and footer designs, originally intended to be applied to corresponding templates. I.e. the "Footer Portfolio" design would be applied to the "Home Portfolio" template.

> I suggest we don't do this, but rather only provide one "footer" template part (and header), which people then have the ability to replace the footer with the provided alternatives. Using this method, the header/footer parts on a site are always in sync — unless the user chooses to create and display a different header on a page.

**Comment by jordesign** [comment]
I've done a sweep of these and #455 is a PR to make the references to the Footer template part consistent. Header template parts looked correct already 👍
