### ISSUE TITLE
Audit pattern names and consider adding descriptions

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfour#465]
Audit pattern names (not only template patterns) so that they are clear and descriptive.
Consider adding pattern descriptions for users who use screen-readers. The description is hidden, not displayed in the interface.

**Comment by MaggieCabrera** [comment]
+1 on the description and that's another good thing to add to the readme file for future reference when building patterns

**Comment by carolinan** [comment]
I am not sure why this was closed? The patterns have no descriptions.

**Comment by carolinan** [comment]
I have opened a trac ticket: https://core.trac.wordpress.org/ticket/59688

**Comment by MaggieCabrera** [comment]
You are right, I´ll reopen

**Comment by MaggieCabrera** [comment]
Ok I just remembered why I closed it: we are past the string freeze so if we add these strings they won't be able to be translated. I don't know if we can add them!

**Comment by carolinan** [comment]
No we can handle it in the trac ticket later.

**Comment by carolinan** [comment]
Core ticket: https://core.trac.wordpress.org/ticket/59688
