### ISSUE TITLE
Unexpected or invalid content error in footer

### ISSUE THREAD

**Issue by benimub** [WordPress/twentytwentyfour#485]
I have clone this theme and checking the homepage I am facing this error in footer in backend.
Error message "This block contains unexpected or invalid content".
![image](https://github.com/WordPress/twentytwentyfour/assets/7359743/452ee585-1fcf-40d7-9a97-0ec87966e9ef)
Also same issue is in this section too.
![image](https://github.com/WordPress/twentytwentyfour/assets/7359743/d8da32a1-5899-41d2-8158-6e1c0023eaeb)

**Comment by MaggieCabrera** [comment]
[Context for this issue](https://github.com/WordPress/twentytwentyfour/pull/403#issuecomment-1731029189)
