### ISSUE TITLE
Replace wrong images in patterns

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfour#488]
This pattern has the wrong image:

| Currently      | Original design |
| ----------- | ----------- |
| <img width="1474" alt="Captura de ecrã 2023-09-22, às 11 28 35" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/573f964d-31aa-46c1-a96d-20487ca303db">     |   <img width="1748" alt="Captura de ecrã 2023-09-22, às 11 38 20" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/dd13d9f7-4224-49ba-8624-dd617f727810">   |

Here's the image that should be used:
![tt4_about_2](https://github.com/WordPress/twentytwentyfour/assets/65220155/939905eb-d586-49aa-8bd1-b5097e0a3b2c)

In this pattern, the image should not be black and white:

| Currently      | Original design |
| ----------- | ----------- |
| <img width="1483" alt="Captura de ecrã 2023-09-22, às 11 29 31" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/cd2b08fa-fbaf-4d35-a3ae-3156feb8c136">   |    <img width="1524" alt="Captura de ecrã 2023-09-22, às 11 36 42" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/9f709010-7d22-4e9c-8bf2-ab3812037a95">   |

Here's the image that should be used:

![pattern_image](https://github.com/WordPress/twentytwentyfour/assets/65220155/cf352e7b-a4f3-42e1-b980-f714205dfa36)

Here the image on the right is also not correct:

| Currently      | Original design |
| ----------- | ----------- |
|   <img width="907" alt="Captura de ecrã 2023-09-22, às 11 41 00" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/1577f60b-0bd9-448c-ba42-ae3f272a5403">   |    <img width="872" alt="Captura de ecrã 2023-09-22, às 11 42 31" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/3577e7b7-e87c-435c-8a7f-b9c4992ba238">   |

Here's the image that should be used:

![project-layout-image-2](https://github.com/WordPress/twentytwentyfour/assets/65220155/3a565f44-911a-443d-a147-5204939b23c5)

**Comment by MaggieCabrera** [comment]
I think @richtabor made these changes to reduce the amount of images that we bundle with the theme. These assets will be loaded into every single WordPress install so we need to be mindful of that

**Comment by beafialho** [comment]
Oh I see, I wasn't aware of that. Can we just make the one in the second pattern not use black and white duotone then?

**Comment by beafialho** [comment]
This appears to be solved so I'm closing it.
