### ISSUE TITLE
Sizing conformity for patterns — rems vs ems vs pixels

### ISSUE THREAD

**Issue by hiyascout** [WordPress/twentytwentyfour#49]
Is a decision in order on block editor sizing units for both fonts and spacing, and/or setting variables?

I think expecting everyone to build first drafts in the same units might be a tall order, but we could aim to convert/conform patterns as we revise, and those of us who are comfortable working in variables/rems could do so from the start. 

In the mockup, here are the sizes: h1 48px, h2 38px, h3 28px, h4 24px, h5 20px, h6 18px, p 14px. (So would 1rem=14px?) 

Context: I'm building the Posts with Sidebar pattern and converting the pixels to rems where I think it works more consistently (horizontal text spacing for a post meta row, etc).

**Comment by melchoyce** [comment]
Related: https://github.com/WordPress/twentytwentyfour/issues/34

**Comment by hiyascout** [comment]
Thank you @melchoyce !   Also noting that in the pattern I'm working on specifically, there are some font sizes that are just short or just bigger than the presets.

**Comment by richtabor** [comment]
Related as well, for spacing: https://github.com/WordPress/twentytwentyfour/pull/102

**Comment by hiyascout** [comment]
If we follow @richtabor's Fibonacci proposal in #102, the fonts could be adjusted as written below. This might stretch past the original vision for the design (especially in that it has two sizes that are larger than the original 48 pt), and the use of two sequences might be convoluted. 

The original sequence (14, 18, 20, 24, 28, 38, 48) doesn't match any Fibonacci sequence, but we could alternate between two Fibonacci sequences (7 and 9). (I picked 7 and 9 because they seemed to have the closest numbers to the original sequence--v. arbitrary.) {But, 7+9 is 16 and there are 16 letters in twentytwentyfour 🤣}

Fibonacci sequence starting at 7 includes:
...14, 21, 35, 56...

Fibonacci sequence starting at 9 includes:
...18, 27, 45, 72...

Combined sequence could be:
14, 18, 21, 27, 35, 45, 56, 72

We could then use fluid font sizes based on this, using an average as the preferred size: 

h1 clamp([56], [64], [72]);
h2 clamp([45], [50.5], [56]);
h3 clamp([35], [40], [45]);
h4 clamp([27], [31], [35]);
h5 clamp([21], [24], [27]);
h6 clamp([18], [19.5], [21]);
p clamp([14], [16], [18]);

This would require that font sizes in patterns that people are building be converted to variables. Is that too far removed from the original vision?

(Also, contributor best-practices question—now that I'm proposing a solution in this issue, should this be proposed within a fork? Or does it make sense to get feedback on it theoretically before I create a fork?)

**Comment by carolinan** [comment]
I think the reason why the theme uses no more than four font sizes is that after that, the control changes and it is a select list instead of the preset buttons.

**Comment by carolinan** [comment]
And I feel strongly that 14 is too small for any text.

**Comment by hiyascout** [comment]
@carolinan I'm with you on 14 being too small -- didn't know if we were still able to suggest design changes to the original. (Also just to clarify, that 'original sequence' comes from the h1-h6 and p tags inside the theme mockup, rather than the SMLXL buttons.)

**Comment by hiyascout** [comment]
Edit: this could use theme.json's fluid options rather than [clamp].

**Comment by MaggieCabrera** [comment]
I think we can close this one now
