### ISSUE TITLE
Full page pattern for RSVP

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/twentytwentyfour#491]
Bea marked this pattern as full page on the demo site and I agree that this makes sense. Let's treat this one the same way we did the newsletter landing one.

http://2024.wordpress.net/index.php/rsvp/

**Comment by carolinan** [comment]
The large text needs to be an H1 heading, but the text rotation (writingMode) is only supported from 6.4 Beta 1 (GB 16.7 is not until the day after the beta) so when should this be updated?

**Comment by carolinan** [comment]
I mean if it is updated before, it works with Gutenberg trunk active, but there will be a block validation error for everyone else who tests the theme and don't have trunk

**Comment by carolinan** [comment]
Should we try to limit it to "page with no title"?
With the default page template, there are two spacer blocks above the group with the green background.
Or maybe it is not possible to select specific templates only template types 😞
