### ISSUE TITLE
Javascript warning in the home template in the Site Editor

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfour#502]
**Description**
In the Site Editor, there is a JavaScript warning when you view the default home template.

`Warning: Encountered two children with the same key, `post-meta`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.`

I did some manual testing, and this seems to be because one of the patterns uses the post-meta template part, twice,
but more testing is always helpful.

**Opinion:** Reading the warning, this seems to be intentional. I don't know the background to it, but if there are good reasons why a template part can not be used twice in the same template, then it should be solved in the theme.

**Step-by-step reproduction instructions**
Open the home template in the Site Editor and see the JS warning in the browser console.
In posts-featured.php, remove one of the two post-meta template parts.
Confirm that the warning disappears.

**Comment by carolinan** [comment]
So, I manually created a custom template through the UI, and added the post meta template part twice. The warning appeared. (though not until I had saved and then refreshed the editor a few times).

**Comment by carolinan** [comment]
If this is a React warning I don't see how we can solve it without removing one of the parts?

**Comment by MaggieCabrera** [comment]
I think this is a react warning, but the meta is showing twice. I think it should be fixed, but I'm not 100% confident, so I'll open a GB PR and ask for help reviewing

**Comment by MaggieCabrera** [comment]
https://github.com/WordPress/gutenberg/pull/54861

**Comment by carolinan** [comment]
I believe this can be closed?

**Comment by MaggieCabrera** [comment]
Yes, this was fixed upstream
