### ISSUE TITLE
Footer copyright says 2024 not 2023

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfour#510]
**Description**
Oops, can we at some point **before the string freeze** change this to 2023?

**Comment by MaggieCabrera** [comment]
I'm not too happy with this string, can this be something else? @beafialho Else we are going to need to update it next year, cause the theme name is TT4...

**Comment by beafialho** [comment]
You're referring to the portfolio footer, correct? We can remove the copyright and just use "Twenty Twenty-Four".

<img width="1724" alt="Captura de ecrã 2023-09-26, às 15 11 38" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/6e8ab88a-03ef-4cad-84b5-eabc75e1d734">

**Comment by carolinan** [comment]
(This would be the site title block)

**Comment by beafialho** [comment]
Could be the site title block as long as the appearance matches the screenshot above 👍🏼

**Comment by jordesign** [comment]
I'm currently seeing that footer as having the '© 2024` paragraph and then _also_ the Site title...

So can we just remove `2024` altogether so it would read `© [site title]` ?

<img width="1200" alt="Screenshot 2023-09-27 at 12 39 11 pm" src="https://github.com/WordPress/twentytwentyfour/assets/1842363/b245381d-7f8d-4c68-8cb6-d7b06124ca81">

**Comment by beafialho** [comment]
> So can we just remove 2024 altogether so it would read © [site title] ?

👍🏼
