### ISSUE TITLE
All footers: Remove space in "Designed with WordPress"

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfour#512]
There's an unintentional space behind the words "Designed with WordPress" in every footer, which should be removed.

https://github.com/WordPress/twentytwentyfour/assets/65220155/794f6fd8-09cc-4eff-87e9-dd30c2dbbbd7

**Comment by luminuu** [comment]
As discovered in the linked PR that was closed, this is not an issue of the theme itself, rather something that is coming from Gutenberg. As it's not displayed on the frontend, I think we can be okay with leaving this as is and maybe report that to the Gutenberg repo, as this should happen with every theme and not just specifically with TT4.
