### ISSUE TITLE
Empty block found in the editor

### ISSUE THREAD

**Issue by kafleg** [WordPress/twentytwentyfour#518]
The Empty block for the Site tagline is found in footer.php pattern. That is added for a cause? 

![image](https://github.com/WordPress/twentytwentyfour/assets/13062231/67f1bf85-63a9-432d-a719-54ccc968073c)

**Comment by carolinan** [comment]
It is empty when the site, the installation, has no site tagline. The tagline is not added by the theme.

**Comment by luminuu** [comment]
Can cofirm, it's filled with content when there's a tagline, if there's none, it's empty and won't show.
