### ISSUE TITLE
Buttons: Remove border that gets visible on hover

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfour#520]
Currently when we hover buttons, the border gets visible. Let's remove it so the states look like the design.

**Currently:**

https://github.com/WordPress/twentytwentyfour/assets/65220155/0a521ae3-d862-470d-a72e-3cfe5a8a1409

**Intended:**

https://github.com/WordPress/twentytwentyfour/assets/65220155/2a6de00b-c209-4a4c-8253-197d9794d764

**Comment by MaggieCabrera** [comment]
The border needs to be there so the size of the normal button is the same as the outlined one, but the color of the border on hover does need fixing so it matches the desired behaviour
