### ISSUE TITLE
Theme compatible with builders (Elementor, Divi...)?

### ISSUE THREAD

**Issue by ValentinGratz** [WordPress/twentytwentyfour#523]
**Description**
Good morning,

I just discovered a theme that looks good, and I think I'll use it.

On the other hand, I would like to know if it will be compatible with uilders other than gutenberg, such as Elementor, or Divi among others?

Thank you for your reply,

**Comment by huzaifaalmesbah** [comment]
Thanks for your inquiry! This theme is exclusively for the block editor (Gutenberg).

**Comment by ValentinGratz** [comment]
Thank you
