### ISSUE TITLE
Set default image behavior to expand on click (lightbox)

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#529]
To showcase the new lightbox functionality in core, I propose we set lightbox (Expand on click) on for images. 

- [ ] Update theme.json to reflect lightbox global setting ([source](https://github.com/WordPress/gutenberg/blob/trunk/lib/theme.json#L276-L280))
- [ ] Update patterns that should have lightbox off, like clients

**Comment by carolinan** [comment]
I would strongly recommend against this because the lightbox has multiple issues.
If the lightbox is improved and is accessible in a later release, the theme can be extended with new patterns.

**Comment by richtabor** [comment]
> I would strongly recommend against this because the lightbox has multiple issues.

Can you give sources? This feature is currently planned for 6.4.

**Comment by carolinan** [comment]
The feature doesn't have its own label, here are some:

Tracking issue: https://github.com/WordPress/gutenberg/issues/51132

https://github.com/WordPress/gutenberg/issues/54921
https://github.com/WordPress/gutenberg/issues/54869
https://github.com/WordPress/gutenberg/issues/54916
https://github.com/WordPress/gutenberg/issues/54682
https://github.com/WordPress/gutenberg/issues/54635

There are accessibility issues that I have run into and that I know have been discussed, but right now, I cannot find specific issues for them; they may only be mentioned in other discussions. 
For example, alt texts are not announced, so the only information a screen reader user gets is "Enlarge image" followed by "close"

**Comment by artemiomorales** [comment]
> For example, alt texts are not announced, so the only information a screen reader user gets is "Enlarge image" followed by "close"

@carolinan Thanks for catching this. This had been working previously but had regressed in a recent shuffle of the code. [Here's a PR fixing it](https://github.com/WordPress/gutenberg/pull/55000).

I haven't come across other accessibility issues or been made aware of any. As of the last time accessibility reviewers took a look, it also seemed to be working well, so would appreciate links to those discussions if you or others could surface them 🙏

As far as enabling the lightbox by default goes, I personally don't think that's necessary for core and it can instead be showcased via themes, though am happy to hear other opinions and further thoughts on that.

**Comment by richtabor** [comment]
> As far as enabling the lightbox by default goes, I personally don't think that's necessary for core and it can instead be showcased via themes, though am happy to hear other opinions and further thoughts on that.

Agreed! That's why I'm proposing it here in TT4.

**Comment by artemiomorales** [comment]
> Agreed! That's why I'm proposing it here in TT4.

Got it! Pardon, I missed that this is in the Twenty Twenty Four repo 😆

**Comment by luminuu** [comment]
@carolinan Have you followed the development of the lightbox recently and can you tell us if the A11Y issues have been worked on?

**Comment by carolinan** [comment]
Only some are worked on https://github.com/WordPress/gutenberg/issues?q=is%3Aopen+is%3Aissue+author%3Aafercia+label%3A%22%5BBlock%5D+Image%22
During a test on Friday, Andrea found more problems with the usability, that does not have issues opened yet. I believe he plans to write the dedicated issues today.

**Comment by richtabor** [comment]
There is a [follow-up PR](https://github.com/WordPress/gutenberg/pull/55212) to lightbox ready for testing, but it's an exploration; not a matter-of-fact. Worth a look for sure though.

**Comment by richtabor** [comment]
Going to close this as not-planned. The lightbox feature needs a bit more attention before we should enable it by default out-of-the-box. This is a good PR https://github.com/WordPress/twentytwentyfour/pull/530  to showcase the how though, for future reference.

**Comment by MaggieCabrera** [comment]
Let's make a point of including a patch for TT4 on 6.5 including this change
