### ISSUE TITLE
Pulloquote Block border not displaying.

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/twentytwentyfour#533]
**Description**
Hello Team,

I have worked on theme "**Twenty Twenty Four**" and found that the "**Pulloquote**" block border is not displaying when we trying to apply it from block setting.

**Step-by-step reproduction instructions**
1. Go to page Type / to choose a block
2. Select "**Pullquote**" block
3. Add dummy text
4. Click on block setting and try to set border.

**Expected behavior**

![CleanShot 2023-09-29 at 15 25 28@2x](https://github.com/WordPress/twentytwentyfour/assets/53076293/5a46a1e6-2244-4f25-b167-3288eb433460)

**Screenshots**
Issue Video: (https://share.cleanshot.com/N0Phrr0rJ0HwVW5MN16T)

**Back-end:**
![CleanShot 2023-09-29 at 15 36 43@2x](https://github.com/WordPress/twentytwentyfour/assets/53076293/5527f8f7-37d2-45d0-b047-d790b5dcf93d)

**Front-end**
![CleanShot 2023-09-29 at 15 36 17@2x](https://github.com/WordPress/twentytwentyfour/assets/53076293/4e22e09b-026c-432e-b1c5-92b5fdbf9dec)

**Environment info**
Device: Macbook M1
OS: 13.5.2 (22G91)
Browser: Google chrome
Version: 117.0.5938.132 (Official Build) (arm64)
WordPress version: 6.3.1, Gutenberg 16.7.0, Theme active: Twenty Twenty-Four,

**Comment by zakariabinsaifullah** [comment]
I have fixed the issues and added PR #535. I am waiting for the merge.

**Comment by luminuu** [comment]
Done with #550
