### ISSUE TITLE
Theme installation failed.

### ISSUE THREAD

**Issue by bimalsht** [WordPress/twentytwentyfour#539]
While I install the theme in the latest version of WordPress it show the issue _The package could not be installed. Your WordPress version is 6.3.1, however the uploaded theme requires 6.4._

![Screenshot_6](https://github.com/WordPress/twentytwentyfour/assets/79363609/0df307fd-d379-485e-be5e-0b175ce72fa3)

**Comment by carolinan** [comment]
Hi.
This is correct, the theme only supports WordPress 6.4 and later.

**Comment by kafleg** [comment]
@carolinan But I think the theme should work with two prior versions of WordPress. (_But this guideline was before_).

**Comment by MaggieCabrera** [comment]
> @carolinan But I think the theme should work with two prior versions of WordPress. (_But this guideline was before_).

TT3 did the same thing. TT4 potentially works with 2 versions prior but it will have blocks that are using things the editor doesn't have in those versions (like aspect ratio for example) so it will not look good on those versions.

**Comment by luminuu** [comment]
Ever since Twenty Twenty-One, the default theme has required the version of WP it was shipped with. So we do not need to adjust this and as Maggie explained, we use features that would not work on previous versions.
