### ISSUE TITLE
Pattern file names out of sync with pattern slugs

### ISSUE THREAD

**Issue by felixarntz** [WordPress/twentytwentyfour#548]
**Description**
Several of the pattern files have confusing file names that are out of sync with the actual pattern slugs. While that's not a strict requirement, keeping the file names in sync with the pattern slugs makes working with them more straightforward.

For example:
* https://github.com/WordPress/twentytwentyfour/blob/trunk/patterns/template-home-business.php uses `twentytwentyfour/template-home`. So the file should probably be renamed to `template-home`?
* All the `page-*` patterns (e.g. [this one](https://github.com/WordPress/twentytwentyfour/blob/trunk/patterns/page-01-business-home.php)) use a different slug as well. Why do they include the `page-0x` prefixes in the file name?

There are some higher level concerns regarding a few of the patterns too which I shared in https://core.trac.wordpress.org/ticket/59465#comment:21, though let's focus the issue here on just the discussion on why those file names aren't in sync with the actual pattern slugs?

**Expected behavior**
Pattern file names should match the relevant pattern slug (probably minus the `twentytwentyfour/` prefix).

**Comment by richtabor** [comment]
I think it'd be nice if the file names were named via primary category, like {category}-{slug}.php — though we don't need the category in the pattern's title. There are a few that have been updated like such already. 

For example, the text-centered-title.php pattern (already like this). 

```
/**
 * Title: Centered title
 * Slug: twentytwentyfour/text-centered-title
 * Categories: text, about
 * Viewport width: 1200
 */
```

An exception would be for hidden patterns, which should have 'hidden' in place of the category.

**Comment by richtabor** [comment]
@luminuu would be nice to get #635,  #636 , #637, https://github.com/WordPress/twentytwentyfour/pull/638, https://github.com/WordPress/twentytwentyfour/pull/631, https://github.com/WordPress/twentytwentyfour/pull/630, and https://github.com/WordPress/twentytwentyfour/pull/626 pushed in before the big rename (to prevent conflicts). They're all relatively small. 😅🚀

**Comment by richtabor** [comment]
And perhaps https://github.com/WordPress/twentytwentyfour/issues/624 can be done at the same time as this.

**Comment by richtabor** [comment]
Another thing to note is that patterns are loaded in file-order. Which matters particularly for the starter pattern modal: 

![CleanShot 2023-10-12 at 17 33 51](https://github.com/WordPress/twentytwentyfour/assets/1813435/1f580a4f-5f4b-47d5-b0a1-3119d479bed7)

![CleanShot 2023-10-12 at 17 34 23](https://github.com/WordPress/twentytwentyfour/assets/1813435/84bf20aa-3dc0-4133-b125-1b57a198d325)

**Comment by luminuu** [comment]
@richtabor If you have some time today and want to look into this, feel free to do so. Other things kept me busy today and I merged all mentioned PRs so far.

**Comment by richtabor** [comment]
> @richtabor If you have some time today and want to look into this, feel free to do so. Other things kept me busy today and I merged all mentioned PRs so far.

I may be able to.
