### ISSUE TITLE
H5 and H6 is not having any difference.

### ISSUE THREAD

**Issue by NidhiDhandhukiya74** [WordPress/twentytwentyfour#551]
**Description**

If you check in Heading block with H4 to H6 there is no difference visible between both.

**Step-by-step reproduction instructions**

1. Take Two Heading block for comparison.
2. For first one choose h5 and second one choose h6
3. Use same text so see difference clearly

**Expected behavior**

H5 and H6 is having a little bit of change occur when we change the heading level either font-weight or font-size.

**Video**

Video URL :- https://share.cleanshot.com/Mr7ZkwNfBXprgNqgxwl1

**Environment info**

- Mac OS
- Chrome Browser
- Wordpress 6.3.1
- Gutenberg - 16.7.0

**Comment by MaggieCabrera** [comment]
Looking at theme.json this is indeed what's happening, but looking at the figma, it shouldn't be. Let's change it to follow what figma is suggesting:

https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=401%3A1691&mode=dev

**Comment by luminuu** [comment]
I'd like to have some input here from @beafialho and @richtabor about how we can best achieve this from the design and font sizes perspective.

**Comment by richtabor** [comment]
Are we using either in any patterns/templates?

**Comment by beafialho** [comment]
It seems that the headings in the theme are not at all like the ones in Figma because I believe while building the theme we must have agreed on different size presets or perhaps missed those smaller headings. In any case, I don't think H4, H5 and H6 should be the same size, like now:

<img width="407" alt="Captura de ecrã 2023-10-04, às 12 10 10" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/628db689-fdd4-4469-9911-fb07500a48b0">

I think we should respect Figma's sizes:

<img width="434" alt="Captura de ecrã 2023-10-04, às 12 13 23" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/1059ec5b-84f5-4eee-b11f-b248f32043e2">

**Comment by luminuu** [comment]
We use `h5` in the `pricing` pattern, but we do not use h6 in the patterns at all.

**Comment by richtabor** [comment]
> We use h5 in the pricing pattern, but we do not use h6 in the patterns at all.

An aside, but we should probably not I'm thinking. It's unlikely the other headings on the page will line up.

**Comment by Subodhsun01** [comment]
I checked the heading of the home page template and found that the heading H4, H5 and H6 has the same size.
Go to appearance > editor > templates > blog home
Change the headings of A commitment to innovation and sustainability from H2 to H4, H5 and H6, you can see the size is same of those three headings type.
Testing on:
WordPress Beta 2, 6.4 (fresh install)
Laragon Local server
PHP 8.2
Browser Chrome, Edge
Windows 11

**Comment by Subodhsun01** [comment]
![image (8)](https://github.com/WordPress/twentytwentyfour/assets/110084703/48d927bb-c2d2-412c-a3e8-5040448826bb)

I checked the home page template heading and found that the headings H4, H5, and H6 are the same size.

- Go to appearance > editor > templates > blog home
- Change the headings of A commitment to innovation and sustainability from H2 to H4, H5, and H6, you can see the same size for those three headings type.

Testing on:

- WordPress Beta 2, 6.4 (fresh install)
- Laragon Local server
- PHP 8.2
- Browser Chrome, Edge
- Windows 11
