### ISSUE TITLE
Footer links line height difference in WordPress 6.4 Beta 2 Version.

### ISSUE THREAD

**Issue by trinisha05** [WordPress/twentytwentyfour#560]
**Description**
I installed WordPress 6.4 (Beta 2 Fresh Install) and found footer links line height difference in editor and front view while using Gutenberg plugin.
The list view and line height issue shows without using the plugin also.

**Screenshots**
Front View :
![image](https://github.com/WordPress/twentytwentyfour/assets/87406714/f5f6895d-2066-44ad-890a-1322c788dbcd)

Editor View: 
![image](https://github.com/WordPress/twentytwentyfour/assets/87406714/90f08210-01ef-47fe-b95a-e488a9fd7957)

Without Gutenberg Plugin:
![image](https://github.com/WordPress/twentytwentyfour/assets/87406714/05628efc-8362-41d1-bc1b-94b64a725127)

**Environment info**
Gutenberg Version: Version 16.7.0
PHP: 7.4.28
Browser: Chrome
Laragon Local Server
WordPress 6.4 (Beta 2 Fresh Install)
OS: Windows 11
Active Plugin: Gutenberg

**Comment by kafleg** [comment]
Thank you for testing the theme and creating the issue. 

I also have the same issue as you mentioned.

**Comment by carolinan** [comment]
I am not able to reproduce this.
I see the following CSS that hides the bullets:

```
.wp-block-navigation ul, .wp-block-navigation ul li {
	list-style: none;
	padding: 0;
}

```
Is all the CSS for the navigation block loading on your WordPress installation?

**Comment by huzaifaalmesbah** [comment]
I can't see the bullet.
I installed fresh 6.4-beta-2

| Without Gutenberg | With Gutenberg  |
|-------------------|-----------------|
|<img width="1407" alt="Screenshot 2023-10-04 at 6 24 04 PM" src="https://github.com/WordPress/twentytwentyfour/assets/63150399/59fa1f9e-1248-4e03-8c57-35bab7390edc">|<img width="1391" alt="Screenshot 2023-10-04 at 6 29 24 PM" src="https://github.com/WordPress/twentytwentyfour/assets/63150399/b8d81bd9-e0e4-45e7-bd82-96b53a6e5800">|

**Comment by webashrafians** [comment]
Thank you for sharing this. 
I got it too. 
Although it is not such a big issue. But it is important to solve. 
I solved it with a custom Style.

**Comment by alishabajra** [comment]
Thanks for sharing this!
I also have the same issue as you pointed out. 
Bullets when not using the Gutenberg plugin. No bullets but extra spacing when using the Gutenberg plugin.
![editor](https://github.com/WordPress/twentytwentyfour/assets/35087821/ce4a1cd8-8ff8-4cec-a45e-9167c215955a)
![with-gutenberg](https://github.com/WordPress/twentytwentyfour/assets/35087821/9b0643aa-2287-47ca-a044-11fa7e772510)
![without-gutenberg](https://github.com/WordPress/twentytwentyfour/assets/35087821/eacb8d91-2682-4d93-b44e-3bc68c75e9d6)

**Comment by MaggieCabrera** [comment]
I think we probably need to change the CSS to also apply in the editor

**Comment by Yos0107** [comment]
I also got the same issue.

Editor View (Appearance>editor>blog home)
![image](https://github.com/WordPress/twentytwentyfour/assets/86192032/0e792143-f5e2-45ba-aab0-e78dcaa1bf25)

Frontend View
![image](https://github.com/WordPress/twentytwentyfour/assets/86192032/4ec92e02-bbf5-4e0f-a28f-a02fe49a80cd)
