### ISSUE TITLE
Archive template (No results): Spacing and copy adjustment

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfour#566]
The spacing below the title and above the no results message is way too big at the moment:

| Currently | [Figma](https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=4524-1318&mode=design&t=cqqqMMwPUdJFi9iN-4) |
| --- | ----------- |
| <img width="1736" alt="Captura de ecrã 2023-10-04, às 16 00 43" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/e1af07b4-d4fe-4b3f-93ef-c4a7f0f06ad5">  |  ![Archive Template_ No results](https://github.com/WordPress/twentytwentyfour/assets/65220155/fcf5584d-260f-47ce-b680-79df96b21570) |

The text also should say instead **"No posts were found."**

**Comment by beafialho** [comment]
Also applies to Search (No results):

<img width="1317" alt="Captura de ecrã 2023-10-04, às 16 27 09" src="https://github.com/WordPress/twentytwentyfour/assets/65220155/b8f9ad26-01b2-4114-a0b3-171a47a09ce0">

See [Figma](https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=615-10850&mode=design&t=cqqqMMwPUdJFi9iN-4)

**Comment by luminuu** [comment]
Done with #571
