### ISSUE TITLE
Two posts patterns look broken in the site editor > patterns view

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#568]
![CleanShot 2023-10-04 at 11 59 14](https://github.com/WordPress/twentytwentyfour/assets/1813435/ff009322-8b27-41d3-ac28-a2db8a0e627c)

**Comment by MaggieCabrera** [comment]
Mmmh, they could look better, but can you test on a site that has 3 posts?

**Comment by richtabor** [comment]
Probably shouldn't be bunched up to the edge of the preview as well. 

![CleanShot 2023-10-04 at 12 09 41](https://github.com/WordPress/twentytwentyfour/assets/1813435/9fffde77-6302-4884-88e5-3f8960e1d6b7)

**Comment by MaggieCabrera** [comment]
I think that happens because those are query block patterns, so the pattern doesn't have the wrapper surrounding them. That way they show in the replace/insert flow for the block, which I'd argue is the main case for inserting this kind of block

**Comment by richtabor** [comment]
There's got to be a way to make them look nice though..

**Comment by luminuu** [comment]
Here's a comparison of those patterns when there are more posts, some with featured images:

<img width="910" alt="CleanShot 2023-10-09 at 11 12 40@2x" src="https://github.com/WordPress/twentytwentyfour/assets/7585600/d7ace736-e8ba-4c66-8b3f-594a07d3a9bb">

I think it's okay, just like Maggie said, they're supposed to be used in a query loop so they will have a wrapper element where no extra spacing is needed.

**Comment by richtabor** [comment]
> I think it's okay, just like Maggie said, they're supposed to be used in a query loop so they will have a wrapper element where no extra spacing is needed.

If they're not meant to be used elsewhere, can we hide them?

**Comment by richtabor** [comment]
For example, I wouldn't show those to a client as-is—all the other patterns look ace in the Patterns view.

**Comment by luminuu** [comment]
@MaggieCabrera What do you think about hiding the two patterns in question?

**Comment by MaggieCabrera** [comment]
we can do that, but if you look at the category "Posts" inside the Pattern inserter you will see the patterns that come from core have the exact same problem:

<img width="291" alt="Screenshot 2023-10-11 at 12 06 58" src="https://github.com/WordPress/twentytwentyfour/assets/3593343/55d46a4a-7db0-4b56-8eef-f6f11123aa19">

**Comment by MaggieCabrera** [comment]
In the end I feel like we keep burying features deeper and deeper

**Comment by scruffian** [comment]
To me this seems to be an issue with the way the preview works - maybe the preview should always insert a wrapper to give a bit of extra padding?

**Comment by luminuu** [comment]
> To me this seems to be an issue with the way the preview works - maybe the preview should always insert a wrapper to give a bit of extra padding?

I'd agree to this. I'd prefer to keep them and make the previews a bit nicer. Can you check if there's already an issue in the Gutenberg repo or if we have to open one?

**Comment by richtabor** [comment]
> In the end I feel like we keep burying features deeper and deeper

It's not burying, it's surfacing at the correct context. If these are patterns leveraged with the query loop block, then you should see them when picking a variation from the query loop block - not all the time. 

The same follows for the page patterns, and moving them to a "Pages" category (https://github.com/WordPress/twentytwentyfour/pull/631). They're not sprinkled throughout the other content patterns, but localized where the expectation is that these inserted patterns are meant to be full page designs. 

We don't want everything always everywhere, but to tailor the experience and surface what's significant when it's significant.

**Comment by richtabor** [comment]
If you choose one of these and add it to a page (like any other pattern) does it look fine, or is it edge-to-edge? 

I'm just not following how 95% of our patterns can look ace, but these few can't.

**Comment by MaggieCabrera** [comment]
> If you choose one of these and add it to a page (like any other pattern) does it look fine, or is it edge-to-edge?
> 
> I'm just not following how 95% of our patterns can look ace, but these few can't.

I understand, but it does feel weird that the core patterns have this issue and they will still be there showing this problem (in fact they show up before the theme ones do on the sidebar inserter).

I'm not going to block this, but I think this is a wider concern.
