### ISSUE TITLE
Milky color contrast issue

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwentyfour#570]
**Description**

Moving this out of the WCAG issue for visibility.

The base color #F2EFE6 and contrast 2 #7a6f5c only has a contrast ratio of 4.29:1.
It needs to be 4.5:1 for regular text and 3:1 for large text.

This means that several plain text element as well as the hovered buttons has too low contrast against the background.

**Comment by luminuu** [comment]
@beafialho Can you have a look at this and suggested a better color that matches the accessibility requirement?

**Comment by luminuu** [comment]
I just merged a PR from @richtabor earlier today where the Milky style variation was renamed to Fossil and also contained updated colors. I did a contrast check on those and they look good.
