### ISSUE TITLE
Change RSVP back to a standard pattern

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#575]
The `twentytwentyfour/rsvp-landing` pattern is not a full page design. In contrast, the newsletter pattern is designed as a fullscreen experience (with centered content, etc). 

I don't think this pattern looks great fullscreen; because of the varying placements of content. I propose removing it as a starter pattern. 

Pictured as a fullscreen pattern: 
![CleanShot 2023-10-06 at 14 29 19](https://github.com/WordPress/twentytwentyfour/assets/1813435/175752a0-aaca-433f-873e-259023c29c5f)

**Comment by luminuu** [comment]
@carolinan I think you worked on making this pattern a fullscreen pattern. Do you want to give feedback on this?

**Comment by carolinan** [comment]
I have no opinion, I was just working on the open issue.

**Comment by carolinan** [comment]
The only thing to mind is that the RSVP large text needs to be a heading, not a paragraph.

**Comment by MaggieCabrera** [comment]
I thought it made sense as a full page pattern. Happy to revert if we agree that it is not. @beafialho what is your opinion on this?

**Comment by richtabor** [comment]
> I thought it made sense as a full page pattern. Happy to revert if we agree that it is not. @beafialho what is your opinion on this?

I would too, but you can't publish this as its own page and it'll look alright. The newsletter pattern in contrast is full screen and looks like a landing page.

**Comment by beafialho** [comment]
This pattern makes sense as a full page pattern to me as well. Maybe it's just a matter of using a full height cover and setting content to be full width with spacing presets as margins? It looks better on its own already, check it out in [this link](http://2024.wordpress.net/index.php/rsvp/).

**Comment by richtabor** [comment]
Can it work as a group block instead of a cover block? 

The cover block will cause issues with theme variations, as it auto-applies an overlay of `black` when a color isn't found (which not every variation has the same number of accent colors). That's why I had to change the newsletter pattern to a group: https://github.com/WordPress/twentytwentyfour/pull/576/files#diff-8cc59744df2184bc8af5fae4fb529cab633e8bbff03414d74935e593aad65e35

**Comment by beafialho** [comment]
If we can make the group be full height, I think so.

**Comment by richtabor** [comment]
> If we can make the group be full height, I think so.

I was able to adjust it here as part of this pr: https://github.com/WordPress/twentytwentyfour/pull/638
