### ISSUE TITLE
More Granular Font Sizes

### ISSUE THREAD

**Issue by gregoryfu** [WordPress/twentytwentyfour#577]
It seems like I have to constantly resort to manually specifying font sizes because the set sizes (Small, Medium, Large, etc) are so far apart. For example, the Medium font size calculates to about 16px, while the Large font size calculates to about 26px.

I'd like to see more granular font sizes.

**Comment by luminuu** [comment]
From a design perspective, what do you think @beafialho @richtabor?

**Comment by richtabor** [comment]
I think the font sizes work well out of the box for the theme. This is small, medium, large, extra large, 2x large: 


![CleanShot 2023-10-10 at 15 01 12](https://github.com/WordPress/twentytwentyfour/assets/1813435/c80141c1-6924-482f-82d0-fa4c987d54d7)

**Comment by MaggieCabrera** [comment]
I think they are fine too. To be more granular we should are more options and that would turn the size selector into a dropdown, which I don't think we really have a reason to justify.

**Comment by beafialho** [comment]
I also think they are fine.

**Comment by luminuu** [comment]
Closing this as we have enough voices to keep the current font size setup.

**Comment by kafleg** [comment]
@gregoryfu Can you please share your WordPress.org username?

**Comment by kafleg** [comment]
@gregoryfu never mind, I found it.
