### ISSUE TITLE
WP6.3: No header and footer displayed

### ISSUE THREAD

**Issue by webmandesign** [WordPress/twentytwentyfour#579]
**Description**

First, as I can see the theme should be tested with Gutenberg enabled, I'm not even sure if this is a bug.

When I test the theme with WP6.3 _(without Gutenberg plugin active)_, there are no site header and footer template parts displayed in templates that display `patterns\template-*` patterns.

To resolve I have to add `"theme":"twentytwentyfour"` to affected template part blocks in those patterns to make them work.

Is this intentional? Will the theme be incompatible with older WP versions?

**Comment by huzaifaalmesbah** [comment]
Thanks for creating an issue.
This theme requires a minimum of 6.4 WordPress version for proper functionality. you can check [here](https://github.com/WordPress/twentytwentyfour/issues/197)

**Comment by webmandesign** [comment]
Cool, I thought so. You can close the issue if this is not reconsidered :)

**Comment by carolinan** [comment]
This bug was fixed in WordPress 6.4:
https://github.com/WordPress/gutenberg/pull/54595

**Comment by MaggieCabrera** [comment]
Yes, it wouldn't be the only issue on a 6.3 install without the GB plugin, so we are going to keep 6.4 be a requirement for TT4. Thanks for the report!
