### ISSUE TITLE
Full width blocks not take full width

### ISSUE THREAD

**Issue by amedv** [WordPress/twentytwentyfour#58]
All full width blocks squeezed after publishing (before they looked good).

<img width="1440" alt="Screen Shot 2023-08-24 at 4 47 25 PM" src="https://github.com/WordPress/twentytwentyfour/assets/8436014/9a086dd5-3ef8-4113-9407-53d77cdd062b">
<img width="1436" alt="Screen Shot 2023-08-24 at 4 47 03 PM" src="https://github.com/WordPress/twentytwentyfour/assets/8436014/8854c92c-d804-450d-b19b-fb0bbed6b557">

**Comment by richtabor** [comment]
This has been resolved on the pattern front; some were missing the correct width attributes.
