### ISSUE TITLE
Prepare for string freeze

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/twentytwentyfour#584]
The 17th of October is the RC1 and the hard string freeze, so let's review the theme and make sure every string is marked properly for translation and has good contextual text when needed. 

@beafialho @richtabor, if you have the time to have a look before then in case any text doesn't sound good or needs some tweaking it would be amazing.

**Comment by richtabor** [comment]
There are a lot of inconsistencies on casing across the board. 

### Translation functions: 
For translation functions we have [sentence case](https://github.com/WordPress/twentytwentyfour/blob/trunk/patterns/faq.php#L27) and [title case](https://github.com/WordPress/twentytwentyfour/blob/trunk/patterns/services-cta.php#L38). 

### Pattern titles:
The same follows for pattern titles. We have [sentence case](https://github.com/WordPress/twentytwentyfour/blob/trunk/patterns/columns.php#L3C4-L3C36) and [ title case](https://github.com/WordPress/twentytwentyfour/blob/trunk/patterns/services-cta.php#L3C4-L3C36).

These should all also be sentence case.

**Comment by richtabor** [comment]
Translation functions look good to me, now that https://github.com/WordPress/twentytwentyfour/pull/671 is in.
