### ISSUE TITLE
Simplify HTML for `twentytwentyfour/intro-text-left` pattern

### ISSUE THREAD

**Issue by webmandesign** [WordPress/twentytwentyfour#597]
**Is your feature request related to a problem? Please describe.**

The "Heading on left" pattern (`patterns/hidden-hidden-intro-text-left.php`) has a H1 heading within Columns block. This can be simplified using Group block instead.

---
**Possible additional issue**

Also, the file name has 2 `hidden-` prefixes. Is this a bug or is this intentional?

**Comment by MaggieCabrera** [comment]
the name is a bug!

**Comment by webmandesign** [comment]
I went ahead and renamed the file in #598, which obviously messed up file comparison. Please let me know if this is OK or I should revert the filename change.
