### ISSUE TITLE
Related Gutenberg Issues and PRs

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwentyfour#6]
Let's use this issue to track and prioritize issues that are needed for the theme.

## Must have
- https://github.com/WordPress/gutenberg/issues/54562
- https://github.com/WordPress/gutenberg/issues/36951#issuecomment-1674411656
- https://github.com/WordPress/gutenberg/pull/54609
- https://github.com/WordPress/gutenberg/issues/51347
- https://github.com/WordPress/gutenberg/issues/48081
- https://github.com/WordPress/gutenberg/pull/53725
- https://github.com/WordPress/gutenberg/pull/54418 (a11y concern)
- https://github.com/WordPress/gutenberg/pull/54595

## Nice to have
- https://github.com/draganescu/wp-format-enabler (exploration born of https://github.com/WordPress/gutenberg/issues/53049)
- https://github.com/WordPress/gutenberg/issues/53806
- https://github.com/WordPress/gutenberg/issues/50319
- https://github.com/WordPress/gutenberg/pull/53175
- https://github.com/WordPress/gutenberg/issues/51480
- https://github.com/WordPress/gutenberg/issues/54185
- https://github.com/WordPress/gutenberg/issues/47993
- https://github.com/WordPress/gutenberg/issues/54227
- https://github.com/WordPress/gutenberg/issues/52169
- https://github.com/WordPress/gutenberg/issues/44582

**Comment by carolinan** [comment]
Writing mode and text orientation:
https://github.com/WordPress/gutenberg/issues/50319

-Only basic vertical text with writing-mode CSS is implemented in Gutenberg. -Not in core.
-It is only supported by the paragraph block and partially by the post navigation link (next/previous) block.

Looking at the design, I am unsure of if vertical heading blocks are needed or if it should be a paragraph:
https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=565-10707&mode=design&t=05JjOC2jz5Ty2t6o-0


"Upside down" text, PR has now been merged: https://github.com/WordPress/gutenberg/pull/53175

**Comment by carolinan** [comment]
Allow `aria-hidden` on group, image, and paragraph blocks to support hiding decorative glyphs.
An issue needs to be opened for this.

**Comment by carolinan** [comment]
From @richtabor:

We really need placeholders to support height/width/aspect ratio so we don't have to bundle images. https://github.com/WordPress/gutenberg/issues/48081

**Comment by richtabor** [comment]
For swapping templates: https://github.com/WordPress/gutenberg/issues/51347

**Comment by hanneslsm** [comment]
[Separator is not visible when inside row or stack came](https://github.com/WordPress/gutenberg/issues/47993) up in #152

**Comment by colorful-tones** [comment]
We might want to move #193 to 'Nice to Have'? Based on it recently being closed, and the last comment from @scruffian 

> Yeah I agree this is a general issue with the editor. I have raised an issue for it here: https://github.com/WordPress/gutenberg/issues/54185

**Comment by carolinan** [comment]
Aria-label for navigation block placeholders https://github.com/WordPress/gutenberg/pull/54418

**Comment by carolinan** [comment]
Let's place the search term in the search title inside a `<span>` so that the term can be styled the same way as the query title. A new issue needs to be created for this.

**Comment by hanneslsm** [comment]
Changing the border radius of the search input field on a global level: https://github.com/WordPress/gutenberg/issues/51617
via https://github.com/WordPress/twentytwentyfour/issues/389

**Comment by carolinan** [comment]
> Aria-label for navigation block placeholders [WordPress/gutenberg#54418](https://github.com/WordPress/gutenberg/pull/54418)

This has been merged, but the Gutenberg 16.7 RC1 is on September 20th (originally planned on September 13th).

**Comment by carolinan** [comment]
Bug: The index patterns are not showing for the index template
https://github.com/WordPress/gutenberg/issues/54776

**Comment by MaggieCabrera** [comment]
> Bug: The index patterns are not showing for the index template [WordPress/gutenberg#54776](https://github.com/WordPress/gutenberg/issues/54776)

Is it maybe the same bug the home page had? where we needed to add `Post Types: page, wp_template` to the pattern that wasn't showing

**Comment by carolinan** [comment]
I tried it (in different combinations) but it did not help.
It is available in the block inserter. But there is no large modal with the pattern selection when you reload the page.

**Comment by annezazu** [comment]
Noting that there's a comment here that this issue is important for TT4: https://github.com/WordPress/gutenberg/issues/44582 Can we get it added? Going to keep in the 6.4 board to be safe right now.

**Comment by MaggieCabrera** [comment]
> Noting that there's a comment here that this issue is important for TT4: [WordPress/gutenberg#44582](https://github.com/WordPress/gutenberg/issues/44582) Can we get it added? Going to keep in the 6.4 board to be safe right now.

It's not a deal breaker but it would be a much better user experience if we have it, thank you
