### ISSUE TITLE
Calendar Widget's contrast on Onyx style

### ISSUE THREAD

**Issue by JosephGabito** [WordPress/twentytwentyfour#605]
The TT4 theme looks amazing! 😍

Just found a small thing regarding the good old calendar widget, which I believe the contrast can be improved a bit. Here is how the calendar widget appears with the Onyx style selected:

![CleanShot 2023-10-11 at 05 53 59@2x](https://github.com/WordPress/twentytwentyfour/assets/81974552/47fb8a4b-59fe-4d59-afd9-bd629332a7b3)

Thanks! 😊👍

**Comment by MaggieCabrera** [comment]
Ugh, I think this is a general issue with the calendar block in darker themes, but there's definitely something TT4 can do to improve it, thanks for reporting
