### ISSUE TITLE
Post template visual improvements

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfour#612]
I don't think the post template was looking like this previously, but if we look at the Figma designs, it currently has a lot of inconsistencies:

- Tags block appears twice
- The separator has the wrong color and it should be wide width
- The "Comments" heading should not be there
- There's a lack of padding in the "Leave a reply" section and in the post pagination

Here's a recording of what I mean and what should be adjusted:

https://github.com/WordPress/twentytwentyfour/assets/65220155/464ebb75-bf7c-4d76-ba68-6c6ad7801693

**Comment by luminuu** [comment]
When I remember right the Comments header has to be there in order to ensure a correct heading structure to match the  accessibility requirements. Is that correct @carolinan ?

I'll take a look at the other things you mentioned.

**Comment by MaggieCabrera** [comment]
I'm having a look at this, there are some regressions from the formatting refactor. 

The comments title is there for accesibility reasons
