### ISSUE TITLE
Remove button block border

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#613]
We should remove the border applied to buttons (or make it transparent perhaps). Otherwise when you change the background color, the border is still applied and there's no clear way to remove it.

![CleanShot 2023-10-11 at 11 31 27](https://github.com/WordPress/twentytwentyfour/assets/1813435/0e30e903-c272-430b-9965-c0263427dfcf)

**Comment by luminuu** [comment]
The problem is having no border there means the button is smaller than the outlined button next to it, as it will not have a border. I'd say it's the same if you use a transparent border. I orginally fixed this to ensure both button styles have the same visual size. The border color can be changed in the border settings.

**Comment by carolinan** [comment]
(If the outline style was deregistered, this would be a non issue)

**Comment by richtabor** [comment]
I don't think it should be deregistered, but I think the color issue is bigger than the buttons not being the same size.

**Comment by richtabor** [comment]
> The border color can be changed in the border settings.

This would _maybe_ be enough, if there was a visual indicator that a border is applied in the first place.

**Comment by richtabor** [comment]
Also worth noting the outline button comes with it's own padding as well: 

![CleanShot 2023-10-11 at 11 55 03](https://github.com/WordPress/twentytwentyfour/assets/1813435/5476ce28-bbad-4880-b3e8-e2fff90458f1)
![CleanShot 2023-10-11 at 11 55 32](https://github.com/WordPress/twentytwentyfour/assets/1813435/96bae7f2-dedc-435d-9c24-6df3b8cb0947)

We'll need to target the padding of the outline variation it looks. Here's from the fossil variation, which makes the buttons a good bit bigger: 
![CleanShot 2023-10-11 at 11 55 52](https://github.com/WordPress/twentytwentyfour/assets/1813435/d63edb57-1a73-476e-ac9a-424496115a94)

**Comment by webmandesign** [comment]
> The problem is having no border there means the button is smaller than the outlined button next to it, as it will not have a border. I'd say it's the same if you use a transparent border.

Setting `transparent` border color resolves the issue from the point of outline and filled button size.

**Comment by hanneslsm** [comment]
>Also worth noting the outline button comes with it's own padding as well

Related: https://github.com/WordPress/gutenberg/issues/52636
