### ISSUE TITLE
Spaces in every heading and paragraph

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfour#615]
**Description**

I'm seeing spaces before and after pretty much every heading and paragraph in the theme's patterns, including full page ones.

**Step-by-step reproduction instructions**
1. Add a pattern.
2. Notice the space before a heading and/or paragraph.

**Expected behavior**
There should be no extra spaces neither before nor after headings or paragraphs.

**Screenshots**

https://github.com/WordPress/twentytwentyfour/assets/65220155/c1628fe2-a32f-4a94-a139-941134e7952e

https://github.com/WordPress/twentytwentyfour/assets/65220155/bbce94ca-fcbb-4f7b-8fbc-374476015ec7

**Environment info**

 - Device: Apple M1 Max
 - OS: Ventura 13.4.1
 - Browser: Safari 16.5.2

**Comment by carolinan** [comment]
Good find,
this is probably another formatting issue, where new line breaks have been added, and should be easy to solve.

**Comment by beafialho** [comment]
I just noticed this includes buttons in the patterns as well.

**Comment by MaggieCabrera** [comment]
Let's document this in the readme file on a section about formatting block markup for the future

**Comment by webmandesign** [comment]
I think this happened during auto (?) formatting in #585.

When dealing with actual text content of a HTML tag (block), it should have no line break before and after.
For example, the
```html
<summary>
	<?php echo esc_html_x( 'What is your process working in smaller projects?', 'Question on the details block', 'twentytwentyfour' ); ?>
</summary>
```
should turn into
```html
<summary><?php echo esc_html_x( 'What is your process working in smaller projects?', 'Question on the details block', 'twentytwentyfour' ); ?></summary>
```

(Surely, you can have line breaks within `<?php` and `?>` tags if needed.)
