### ISSUE TITLE
Consider moving the "No results" block in the archives template

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#622]
**Description**
Is it expected to have the "No post found" within the site editor archives template view? If so, we should consider moving it below the post template within the query loop. And follow-up on the Gutenberg side to figure out a better solution. 

**Step-by-step reproduction instructions**
Go to the Site Editor, click on the "All Archives" template. 

**Visual:** 
![CleanShot 2023-10-12 at 10 48 35](https://github.com/WordPress/twentytwentyfour/assets/1813435/4053c155-0a78-4da0-b0e1-393c006cb793)

**Comment by luminuu** [comment]
It has been moved up recently, as when it's below, there will be a giant gap between the heading and the "No results" line: https://github.com/WordPress/twentytwentyfour/pull/571

**Comment by richtabor** [comment]
Gotcha, yea neither is ideal :/

**Comment by luminuu** [comment]
I know. But in the end the frontend view should be preferred and it will either display the "No results" line closer to the headline or actual content. Maybe as an idea, if there can be some visual indicator in the backend that these blocks are an either-or-state, that could help understanding why this block is there better.

**Comment by richtabor** [comment]
> Maybe as an idea, if there can be some visual indicator in the backend that these blocks are an either-or-state, that could help understanding why this block is there better.

Yea. Do you know if there's an issue on this in Gutenberg yet?

**Comment by luminuu** [comment]
> Yea. Do you know if there's an issue on this in Gutenberg yet?

No, I have no idea. I'd have to search for it myself. Not even sure what keywords to search for.

**Comment by carolinan** [comment]
When the block was built, there was a brief discussion about it but I don't think an issue was created.
One example of how to solve it can be seen in WooCommerce where you have the empty cart and filled cart in the same cart block.
