### ISSUE TITLE
Remove duplicative "template" title from template patterns

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#623]
I don't think it's necessary to include the "template" label appended to each template. The UI already indicates that these are templates. 

![CleanShot 2023-10-12 at 10 52 38](https://github.com/WordPress/twentytwentyfour/assets/1813435/88802c49-0ac4-4200-9f80-45db3cd86ff1)

**Comment by luminuu** [comment]
I'll work on this, I just saw you merged #616, so I'm good to go. Also together with #548.

**Comment by richtabor** [comment]
> Also together with https://github.com/WordPress/twentytwentyfour/issues/548.

Are you working on this?

**Comment by luminuu** [comment]
Yes, I want to hop on this tomorrow my morning.

**Comment by richtabor** [comment]
> Yes, I want to hop on this tomorrow my morning.

Sweet!

**Comment by richtabor** [comment]
I think it'd be nice if the file names were named via primary category, like {category}-{slug}.php — though we don't need the category in the pattern's title. There are a few that have been updated like such already. 

For example, the text-centered-title.php pattern (already like this). 

```
/**
 * Title: Centered title
 * Slug: twentytwentyfour/text-centered-title
 * Categories: text, about
 * Viewport width: 1200
 */
```

An exception would be for hidden patterns, which should have 'hidden' in place of the category.
