### ISSUE TITLE
Change references to "Writer" template

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#624]
I propose we simplify the naming convention a bit for the writer template. The others are classification of sites, i.e. a business site, or a portfolio site, whereas "writer" is not a type of site.

Perhaps we should rename it to "Blog" instead. 

![CleanShot 2023-10-12 at 10 53 53](https://github.com/WordPress/twentytwentyfour/assets/1813435/b8c12316-1f9b-42c2-a52a-2ec965d6dc0d)

**Comment by beafialho** [comment]
I agree, this makes sense.
