### ISSUE TITLE
Duplicate tags block on single post template

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#625]
On the single posts template, the tags block is added twice. 

![CleanShot 2023-10-12 at 11 12 29](https://github.com/WordPress/twentytwentyfour/assets/1813435/e8db05bf-8de9-43f9-86ea-ebdd01cdb0bc)

**Comment by beafialho** [comment]
Also mentioned in #612

**Comment by luminuu** [comment]
That fix is already in PR #614, but this needs a little update to be merged.
