### ISSUE TITLE
Layout Width Issue in Rust Variation in Big Screen

### ISSUE THREAD

**Issue by shail-mehta** [WordPress/twentytwentyfour#664]
Layout Width Issue in Rust Variation: max-width:1280px should same for all style variations  

Rust : https://prnt.sc/om3ZEql06f_V

Mint : https://prnt.sc/rsgeWV5xhlZC 
Sandstrom :https://prnt.sc/VMkIBXFbib-5 
Ice : https://prnt.sc/X2afqcisvUqS 
Fossil : https://prnt.sc/x_u7sem2vqlJ
Onyx : https://prnt.sc/xzMlS87Hd8ud

**Comment by shail-mehta** [comment]
PR: https://github.com/WordPress/twentytwentyfour/pull/665

**Comment by MaggieCabrera** [comment]
https://github.com/WordPress/twentytwentyfour/pull/649 is going to include a fix for this

**Comment by shail-mehta** [comment]
Closing this issue because it will fix in https://github.com/WordPress/twentytwentyfour/pull/649
