### ISSUE TITLE
Improvement Mobile Menu View

### ISSUE THREAD

**Issue by kafleg** [WordPress/twentytwentyfour#678]
I know that this issues must be addressed from Gutenberg/core. But I created the issue here if we can do anything from theme as well.

The navigation menu of theme in mobile version can be better. If there are 2/3 level of sub-menus, we can't really recognize them easily which is the parent menu and which is the sub-menus. 

Can we make it better?

![image](https://github.com/WordPress/twentytwentyfour/assets/13062231/6ea70527-443b-4921-beb5-1b1addfb3f0b)

**Comment by kafleg** [comment]
Also, I don't see the use of scroll bar here,
![image](https://github.com/WordPress/twentytwentyfour/assets/13062231/8199bda9-3463-4a67-8e56-c9fef5f11194)

**Comment by beafialho** [comment]
I totally agree this needs to be addressed in Gutenberg, the current display of the navigation in mobile looks less than ideal. For Twenty Twenty-Four specifically, I added a [mobile mockup to the Figma](https://www.figma.com/file/AlYr03vh4dVimwYwQkTdf6/Twenty-Twenty-Four?type=design&node-id=119-923&mode=design&t=q4RKfCJGCy8q7BNt-4) but perhaps it needed a lot of extra css to achieve it.

![Mobile Menu](https://github.com/WordPress/twentytwentyfour/assets/65220155/5a97300d-2e47-4cac-97b3-689ee1f1d7b0)

**Comment by MaggieCabrera** [comment]
I'm not sure this is something we should add to the theme if we think about the maintenance overhead. I know there are plans to tackle this in the block, and I would be happy to open a patch for TT4 when the block lets you customize the [mobile menu separately as a template part](https://github.com/WordPress/gutenberg/issues/43852)

**Comment by Yari2u** [comment]
Would it at least be possible to make the mobile menu for the Entrepreneur use case left aligned? Most small businesses would probably want their services / products be visible as sub-pages in the navigation. The right alignment makes the mobile menu look so messy that I’m afraid many small businesses might be discouraged from starting to use this theme.

**Comment by MaggieCabrera** [comment]
> I'm not sure this is something we should add to the theme if we think about the maintenance overhead. I know there are plans to tackle this in the block, and I would be happy to open a patch for TT4 when the block lets you customize the [mobile menu separately as a template part](https://github.com/WordPress/gutenberg/issues/43852)

Our team has started discussing this GB issue and I am very hesitant to include this kind of CSS that is not overridable by the user. Hopefully 6.5 will include this feature and we can patch the theme with this fix then
