### ISSUE TITLE
CSS syntax error in theme.json

### ISSUE THREAD

**Issue by fabiorubioglio** [WordPress/twentytwentyfour#692]
**Description**
`theme.json` file, line 477

```
"core/post-comments-form": {
"css": "& textarea, input{border-radius:.33rem}"
}
```

The border-radius rule doesn't apply to the input elements.
It should be: "css": "& textarea, & input{border-radius:.33rem}"

**Comment by luminuu** [comment]
Thanks for the issue, however I just tested this and have to report that adding the second `&` actually breaks the textarea input and makes the border of the text area have no radius. It works as is with the `&` just at the front of the statement.
