### ISSUE TITLE
Correct link in comment?

### ISSUE THREAD

**Issue by hanneslsm** [WordPress/twentytwentyfour#699]
The functions.php has a comment with a link to an issue here.

I do not see how this is related. Sure the link is correct?
https://github.com/WordPress/twentytwentyfour/blob/ded7b86b38027f8193d6163959cd5024056a83f6/functions.php#L47-L48

**Comment by MaggieCabrera** [comment]
I don´t think we should link to the tt4 repo anyway, adding issues links makes sense when there´s a bug fix to look forward in the future, not for expanding on documentation necessarily.
