### ISSUE TITLE
Blocks - Global Styles

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwentyfour#7]
Let’s check all core blocks look like the design making use of the Style Book.

## Text
- [x] Headings
- [x] Paragraph
- [x] List
- [x] Quote
- [x] Code
- [x] Details
- [x] Preformatted
- [x] Pullquote
- [x] Table
- [x] Verse

## Media
- [x] Image
- [x] Gallery
- [x] Audio
- [x] Cover
- [x] File
- [x] Media & Text
- [x] Video

## Design
- [x] Button
- [x] Buttons
- [x] Columns
- [x] Group
- [x] More
- [x] Page Break
- [x] Separator
- [x] Custom Link
- [x] Home Link
- [x] Table of Contents

## Widgets
- [x] Archives
- [x] Calendar
- [x] Categories List
- [x] Custom HTML
- [x] Latest Comments
- [x] Latest Posts
- [x] Page List
- [x] RSS
- [x] Search: https://github.com/WordPress/twentytwentyfour/pull/398
- [x] Social Icons
- [x] Tag Cloud

## Theme
- [x] Navigation
- [x] Site Logo
- [x] Site Title
- [x] Site Tagline

## Not in Style Book
- [x] Avatar
- [x] Comment Template (and any related blocks)
- [x] Embed
- [x] Footnotes
- [x] Classic
- [x] Login/out
- [x] Submenu
- [x] Post Template (and any related blocks)
- [ ] Time To Read
- [x] Query Loop
- [x] Term Description

Full list of blocks: https://wphelpers.dev/blocks

**Comment by MaggieCabrera** [comment]
Time to read is not on core (just GB). I gave a look at all the blocks and didn't find anything strange going on with any of them. Closing this one.
