### ISSUE TITLE
For consideration: handling of Webmentions

### ISSUE THREAD

**Issue by cybeardjm** [WordPress/twentytwentyfour#700]
With the new comments template for Twenty Twenty-Three, webmentions are not properly filtered: they appear both as comment and like or repost…
Expected result: if a comment is a like/repost webmention, the comment is hidden, but the like/repost webmention is shown accordingly.

If Twenty Twenty-Four uses the same template for comments, there's a probability that the same behavior will be encountered too.
At least it should be checked.

PS: I use the Webmention plugin by Pfefferle (+ IndieWeb and Syndication Links plugins). This means one of these plugins might probably have to handle all or part of the styling/behavior.
PS2: I posted this as ticket [#59739](https://core.trac.wordpress.org/ticket/59739) for Twenty Twenty-Three

**Comment by carolinan** [comment]
The output of the comments is a block, and any new features would need to be added to the block in the Gutenberg Plugin.
(Also a  default theme can not include support for plugins, since it would not be possible to support _all_ plugins, it would be very unfair to single out a few selected plugins)

**Comment by MaggieCabrera** [comment]
Yeah, what @carolinan said. Thank you for your ticket, this should be fixed upstream, not in the theme.
