### ISSUE TITLE
Untranslated string found

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwentyfour#711]
Needs to be taken care of in a point release.

https://github.com/WordPress/twentytwentyfour/blob/a96a3ea3c9b7888d347edc12859ce80b848d071a/templates/index.html#L6

**Comment by devmuhib009** [comment]
Created PR #714

**Comment by MaggieCabrera** [comment]
I found more:

https://github.com/WordPress/twentytwentyfour/blob/5e8a9608c8a1515b64aa1d0e41e909760b38ab93/patterns/footer.php#L49

**Comment by carolinan** [comment]
This has been reported on trac, so the GitHub issue can be closed.
https://core.trac.wordpress.org/ticket/60298

**Comment by carolinan** [comment]
@devmuhib009 What is your wordpress.org username? :)

**Comment by devmuhib009** [comment]
username: devmuhib
