### ISSUE TITLE
Question: Should the link custom CSS remain?

### ISSUE THREAD

**Issue by richtabor** [WordPress/twentytwentyfour#716]
The link text-decoration-thickness and underline-offset CSS properties are [added to the theme's custom CSS via theme.json](https://github.com/WordPress/twentytwentyfour/blob/trunk/theme.json#L788), which surfaces the control in the Global Styles view. 

I'm thinking it may not be worth it to keep that there, as it may interfere with folks customizing the theme and not understanding where this CSS is derived from. Thoughts?

![CleanShot 2023-11-01 at 16 39 05](https://github.com/WordPress/twentytwentyfour/assets/1813435/97aba9d9-78d2-418d-b9fa-4c35de6517ca)

**Comment by richtabor** [comment]
cc @luminuu and @MaggieCabrera

**Comment by carolinan** [comment]
I think it would be worth improving the documentation/ the paragraph above the text area instead, if users are struggling.

**Comment by richtabor** [comment]
I'm thinking the likely scenario is that they try to edit styles outside of the theme, but struggle to undo/override this bit of arbitrary CSS. 

Documentation doesn't really solve that.

**Comment by MaggieCabrera** [comment]
This is not the only CSS we are adding via theme.json. Why should we remove this one specifically? I think all instances of the CSS we add are things that can't be changed using the editor but that we still want to retain from the original theme. 

I think this rule is not hard to override, even if done via a stylesheet in the case where the user didn't know where they are coming from.

**Comment by richtabor** [comment]
> This is not the only CSS we are adding via theme.json. Why should we remove this one specifically?

[This CSS](https://github.com/WordPress/twentytwentyfour/blob/trunk/theme.json#L788) is added to the theme top-level, not per block. To be clear, I'm suggesting the CSS is omitted entirely; not moved to a stylesheet. 

> I think this rule is not hard to override, even if done via a stylesheet in the case where the user didn't know where they are coming from.

But you _have_ to discover how/where/what to override — instead of not having anything to override in the first place.

**Comment by MaggieCabrera** [comment]
I looked into this more closely and I think you are right. The correct place for this would be elements/links but that's not possible yet, and the place where this CSS is placed right now is not correctly applying everywhere like in the post comments block etc, so we don't have a consistent experience.

Removing this CSS is not a huge design impact so I think it's safe to remove.
