### ISSUE TITLE
ember style adds default duotone with no way to disable

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress/twentytwentyfour#717]
**Description**
When using the `ember` theme style, the [duotone filter is added ](https://github.com/WordPress/twentytwentyfour/blob/trunk/styles/ember.json#L185-L189)

However, there is no way to disable it. It does not appear in the filters when I attempt to "Customize the appearance of specific blocks for the whole site."  

I'm not sure if this is a bug in the theme or in the site editor. 

**Expected behavior**

As a user, I expect to be able to customize the ember style without writing code. 

**Screenshots**

<img width="268" alt="Screenshot 2023-11-02 at 12 48 14 PM" src="https://github.com/WordPress/twentytwentyfour/assets/622599/6b7b2f4f-09a5-4aaa-bcb3-50102c224680">

**Comment by richtabor** [comment]
Hm, looks like this should have solved it. https://github.com/WordPress/gutenberg/pull/55361

**Comment by aaronjorbin** [comment]
It looks like that is targeted for GB 17.0.  I was testing using the 6.4 branch of core without any Gutenberg plugin. Assuming that works as expected (and I can test tomorrow), I would suggest we close this but make note of it as a known issue in case others have a similar problem. We might also want to target the fix in https://github.com/WordPress/gutenberg/pull/55361 for WP 6.4.1

**Comment by MaggieCabrera** [comment]
I tagged that PR for backport and alerted the editor tech leads, closing this. Thanks for the report!
