### ISSUE TITLE
Is there a way to disable "page patterns" or "creation patterns." when creating new pages

### ISSUE THREAD

**Issue by jamiemarsland** [WordPress/twentytwentyfour#721]
**Description**
I like the way that patterns are surfaced when creating a new page, but after a while it becomes annoying. 

1) What's the best way to disable this behaviour?
2) If you delete a page title the modal is triggered automatically everytime (which becomes annoying)

**Comment by MaggieCabrera** [comment]
This is a very valid concern, but I don't think the theme can do anything about it, sadly. I suggest that you leave this feedback in [the Gutenberg repo](https://github.com/WordPress/gutenberg) instead, so it's addressed there for all block themes instead.
