### ISSUE TITLE
Update to Twenty Twenty Four theme and created templates do not appear

### ISSUE THREAD

**Issue by riveso** [WordPress/twentytwentyfour#724]
**Description**
<I use the Twenty Twenty Three template
I have a website with templates, headers and footers edited in the website editor. However, I went to test the new Twenty Twenty Four theme and the created models do not appear. Also the headers and footers do not exist after the update. Will I have to recreate all the models again? Is there any way to update or pull files already created from Twenty Twenty Three?
-->

**Expected behavior**

**Screenshots**

**Environment info**

**Additional context**

**Comment by carolinan** [comment]
Hi
This is how block themes work in WordPress, it is not specific to Twenty Twenty-Three or Twenty Twenty-Four.
All changes you make to templates and styles are theme specific. 
They are saved in the WordPress database, but only visible when that specific theme is active.

There are several different ways to copy the changes, but they all require multiple, time consuming steps, and if that seems  overwhelming it may be easier to re-create the changes manually.

**Comment by MaggieCabrera** [comment]
There are plans to make the user changes persist in some way between theme switches, but we don't have that tool yet, sadly. We can only do it manually yet as Carolina says.
