### ISSUE TITLE
Pill shape taxonomies background applied outside of the shape

### ISSUE THREAD

**Issue by naokomc** [WordPress/twentytwentyfour#726]
**Description**
In the post meta template part, pill shape background color is applied to the background of the pill shape's boundary `<div>`, not the background of the pill shape `<span>` element.

**Step-by-step reproduction instructions**
1. Go to the Theme Editor and open the Post Meta template part.
2. Select the Categories Block
3. Change the style to "Pill"
4. Change the background color.

**Expected behavior**
The background is applied to the the pill shape `<span>` element.

**Screenshots**
Theme Editor:
<img width="375" alt="Screenshot 2023-11-10 at 10 27 12" src="https://github.com/WordPress/twentytwentyfour/assets/34067/3981a183-ccb7-4eec-8b1f-8cc5a2fcc8b5">

Frontend:
<img width="455" alt="Screenshot 2023-11-10 at 10 35 07" src="https://github.com/WordPress/twentytwentyfour/assets/34067/de4191b2-40c8-4e15-b69d-ee06afcb1ff7">

**Environment info**

 - Device: Mac Desktop
 - OS: OS Ventura 13.4.1
 - Browser: Chorme Version 119.0.6045.105 (Official Build) (arm64)
 - Version: 6.4.1

Originally reported by User sunza on the theme support forum:
https://wordpress.org/support/topic/pill-background-colour-for-categories-in-post-list/

**Comment by MaggieCabrera** [comment]
yeah, the pill shape is specific to this theme, and the editor doesn't really know about it, so we really can't control the color via the site editor controls. Maybe we could disable the controls for this block, but that would disable them for the non-pill shaped version too.
