### ISSUE TITLE
Search button in menu is not displaying the full width

### ISSUE THREAD

**Issue by jobthomas** [WordPress/twentytwentyfour#727]
**Description**

* Add search to header
* Choose display "button only"

Both with "search" as button text or the search icon, there's max width CSS that is overriding what it should be:

![Screenshot 2023-11-13 at 11 19 57](https://github.com/WordPress/twentytwentyfour/assets/8783673/064a00b0-2a2e-45bd-ba49-03746d541911)

**Expected behavior**

It should show the full width:

![Screenshot 2023-11-13 at 11 24 51](https://github.com/WordPress/twentytwentyfour/assets/8783673/6ee51c83-7b06-4bcd-9146-3586f0fe2ba0)

**Comment by MaggieCabrera** [comment]
This CSS is not included by the theme, but by Gutenberg, so maybe this is better reported on the Gutenberg repo

**Comment by jobthomas** [comment]
Cool, will move it there.

**Comment by jobthomas** [comment]
Reported here: https://github.com/WordPress/gutenberg/issues/56081
