### ISSUE TITLE
Twenty twentyfour Live Preview loading hangs

### ISSUE THREAD

**Issue by jp-um** [WordPress/twentytwentyfour#728]
**Description**
On clicking on live preview in themes the theme loading hangs with a ton of JS errors (in console).

**Step-by-step reproduction instructions**

**Expected behavior**
The theme should be live previewed.

**Screenshots**
![image](https://github.com/WordPress/twentytwentyfour/assets/22983794/f787bea6-a7c1-4994-842b-924a0d5d7019)

**Environment info**
Desktop
Chrome Version 119.0.6045.159 (Official Build) (64-bit)
Using Wordpress 6.4.1

**Additional context**

**Comment by MaggieCabrera** [comment]
Those jetpack errors suggest that it's not a theme issue. It could either be a problem with jetpack or a problem in the site editor, but the theme can't do anything about this situation (the theme doesn't even have any JS :D)

**Comment by jp-um** [comment]
In fact you are right, the live preview on ANY official wordpress theme does not work (2022, 2023, etc).

If I activate the theme (directly) without the preview, I can see the new theme in action.

**Comment by MaggieCabrera** [comment]
> In fact you are right, the live preview on ANY official wordpress theme does not work (2022, 2023, etc).
> 
> If I activate the theme (directly) without the preview, I can see the new theme in action.

it could be a bug in Gutenberg, if deactivating plugins makes this still happen, it would be worth reporting in the Gutenberg repo
