### ISSUE TITLE
TT4 Demo site is using unsecured content

### ISSUE THREAD

**Issue by BogdanUngureanu** [WordPress/twentytwentyfour#729]
**Description**
While visiting the demo site of the theme(https://2024.wordpress.net), I've noticed that my browser is displaying a "Not secure" connection in the address bar.

Looking a bit into it, I've noticed that the video we display uses a HTTP link instead of a https one. Besides the video, I've noticed that there are also images and links using HTTP links. We should change those too to their https equivalent.

**Step-by-step reproduction instructions**
1. Go to https://2024.wordpress.net/
2. Notice that the browser displays a Not secure connection
3. Notice that the video element uses a HTTP asset

**Expected behavior**

- The video element should be a HTTPS link so that the browser doesn't display a `Not secure` connection.

**Environment info**
https://2024.wordpress.net/

**Comment by MaggieCabrera** [comment]
hey, thanks for reporting this! is it still happening to you? I changed the video (my browser is not giving me this warning)
