### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by JosefJezek** [WordPress/twentytwentyfour#731]
Could you add Dark Mode using HSL?

Dark Mode has [benefits](https://web.dev/articles/prefers-color-scheme#why_dark_mode) for user experience. Some people prefer it for aesthetic or accessibility reasons. It has other advantages, such as preserving battery life in devices.

source: https://web.dev/case-studies/terra-dark-mode

HSL
- https://web.dev/patterns/theming/color-schemes
- https://web.dev/patterns/theming/hsl-starter-kit
- https://caniuse.com/?search=hsl

Dark and Light Theme Switch
https://web.dev/patterns/theming/theme-switch#html

**Comment by MaggieCabrera** [comment]
The theme provides a darker block style already. After release I wouldn't make a change to the theme that would alter the style of people's styles without allowing them a way to avoid that.
