### ISSUE TITLE
Potential Bug with Child Themes, maybe Multisite Related

### ISSUE THREAD

**Issue by bd-viget** [WordPress/twentytwentyfour#733]
**Description**

Either I am doing something wrong, or there is a bug in WordPress and/or the Twenty Twenty-Four theme, however I am getting an error `Error: The parent theme is missing. Please install the "twentytwentyfour" parent theme.` when trying to set up the most basic of Child Themes. I also believe this could be related to Multisite, but I don't really understand why (based on [my findings](#potential-solution)).

## Steps to Reproduce

1. Create a child theme
    1. Create a new directory: `wp-content/themes/twentytwentyfour-child`
    2. Create a child theme `style.css` file, containing `Theme Name: Twenty Twenty-Four Child` and `Template: twentytwentyfour` ([Screenshot](https://3cd.co/jku6GmrK))
2. Visit WordPress Admin > Appearance > Themes ([Screenshot](https://3cd.co/Z4upR1P2))
3. Activate the Twenty Twenty-Four Child ([Screenshot](https://3cd.co/4guRqZzv))

([Screenshot of Directory Structure](https://3cd.co/yAunNkoB))

### Expected Behavior

Visiting the site with the active child theme displays the [default Twenty Twenty-Four home page](https://3cd.co/OAu7X4L6) with all styles loaded correctly.

### Actual Behavior

1. At first, there is a success message "New theme activated. [Visit site](#)"
2. Reloading the page results in the following error message: "Error: The parent theme is missing. Please install the "twentytwentyfour" parent theme." ([Screenshot](https://3cd.co/xQuN2zbk))
3. Visiting the site results in a blank white screen where the `.wp-site-blocks` element is empty. ([Screenshot](https://3cd.co/yAunNkky))

## Potential Solution

After digging a bit, I backtracked [the error](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-theme.php#L442) and noticed the parent theme couldn't be found because [WordPress is looking](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-theme.php#L420) for an `index.php` file in the parent theme directory when a child theme is in use. Since Twenty Twenty-Four is a block theme and does not require `index.php`, it's unable to locate a valid theme directory, which results in the error.

**Adding an `index.php` file to `wp-content/themes/twentytwentyfour` fixes the issue and causes the child theme to behave normally.**

### Other Things I Have Tried, but didn't work

* Adding a basic `theme.json` file to the Child Theme
* Adding `index.php` to the Child Theme only
* Renaming the child theme & folder

### Other Notes

* This is a fresh, standard WordPress installation (v6.4.1)
* There are no active plugins on the site.
* There are no special directory changes or customizations.
* As mentioned before, **this is a Multisite install**. I tested on a non-Multisite instance (however did have plugins active), but I did **not** get the error and the theme appeared to activate, so maybe it is specific to having Multisite, I just haven't investigated why.
* I would assume patching WordPress would be more difficult than just dropping a blank `index.php` file into the theme (and it doesn't appear to have any affect on anything), so maybe as a temporary solution, `index.php` could be added to the Twenty Twenty-* block themes?

**Comment by carolinan** [comment]
If this is related to the index.php file missing, then it is not a problem with the theme, but with WordPress core and how it detects the parent theme and determines if it is a block theme or classic theme, and the ticket should be moved to the WordPress trac.

**Comment by carolinan** [comment]
I will try to set up the multisite later today or tomorrow. I could not find any related issue already reported on trac, but I will ask around.

**Comment by bd-viget** [comment]
> the ticket should be moved to the WordPress trac.

Thanks @carolinan, that makes sense. I appreciate you verifying this!

**Comment by carolinan** [comment]
I am not able to reproduce this using multisite with subdirectories or with subfolders.

WordPress 6.4.2.
Server: nginx
PHP: 8.1.23
On MacOS 14.2.1
