### ISSUE TITLE
The search block text is overlapping in the admin.

### ISSUE THREAD

**Issue by viralsampat-multidots** [WordPress/twentytwentyfour#734]
**Description**
Hello Team,

I have worked on the theme "**Twenty Twenty-Four**" and found that the "**Search box**" block "**text**" is not displaying properly on the back-end side when we change its typography size and width.

**Step-by-step reproduction instructions**

1. Go to page Type / to choose a block
2. Select "**Search**" block
3. Change its typography size to "XL" from block setting
4. Change the "Search" box width to 25% from the block setting.
5. Update the Page

**Expected behavior**
**Back-end**
<img width="1430" alt="CleanShot 2023-12-01 at 11 45 30@2x" src="https://github.com/WordPress/twentytwentyfour/assets/53076293/051db222-bbb0-4ff1-b0c8-edc5cb5f973f">

**Front-end**
<img width="1440" alt="CleanShot 2023-12-01 at 11 45 46@2x" src="https://github.com/WordPress/twentytwentyfour/assets/53076293/42acb278-8468-4c68-af30-f6aa93529d34">

**Screenshots**
**Back-end**
![CleanShot 2023-12-01 at 11 59 39@2x](https://github.com/WordPress/twentytwentyfour/assets/53076293/59f240d1-1305-4134-83f5-bf98d8f5001b)

Also, I have provided its video.

https://github.com/WordPress/twentytwentyfour/assets/53076293/05bb909c-5956-4529-abbe-daa6e92ab9b6

**Environment info**
Device: Macbook M1
OS: 13.6.1 (22G313)
Browser: Google Chrome
Version 119.0.6045.159 (Official Build) (arm64)
WordPress version: 6.4.1 running, Gutenberg 17.1.3, Theme active: Twenty Twenty-Four,

Thanks,

**Comment by carolinan** [comment]
Hi!
Thank you for the report. This problem does not only affect this theme, but other themes too.
It is already reported by your colleague on the core trac, and I moved it to the Gutenberg GitHub repository: 
https://github.com/WordPress/gutenberg/issues/57722
