### ISSUE TITLE
Avatar block is having issue on editor side when right alignment is applied.

### ISSUE THREAD

**Issue by NidhiDhandhukiya74** [WordPress/twentytwentyfour#736]
**Description**

Avatar block not working as expected when we applied right alignment to the editor side.

**Step-by-step reproduction instructions**

1. Take Avatar block.
2. Apply right alignment.
3. Now check both the side editor and front end.

**Expected behavior**

When we applied right alignment then it should be aligned to the right.

**Video**

I have attached video for better understading.
Video URL :- https://share.cleanshot.com/hgKCd92y0PcNprkPVBm2

**Environment info**

Device :- Macbook M1
OS: 13.6.1 (22G313)
Browser: Google Chrome
Version 119.0.6045.159 (Official Build) (arm64)
WordPress version: 6.4.1 running, Theme active: Twenty Twenty-Four,

**Comment by MaggieCabrera** [comment]
Does this happen in other themes like TT3?

**Comment by MaggieCabrera** [comment]
This is looking like a block issue, we should report it in Gutenberg

**Comment by MaggieCabrera** [comment]
https://github.com/WordPress/gutenberg/issues/54714
