### ISSUE TITLE
page.html has no effect on Frontend?

### ISSUE THREAD

**Issue by AtlasianOnline** [WordPress/twentytwentyfour#737]
Whatever changes I make to the "templates/page.html", I can't see any difference on the front. Normally this element is supposed to be available for single pages. What am I doing wrong?

**Comment by MaggieCabrera** [comment]
You may have made local changes and then those will prevail over any changes made directly to theme files. Go to templates/manage all templates and see if the pages template has any customizations. If so, you can clear them using the 3 dot menu to the right. That will remove any changes done via the editor and go back to using whatever is on the theme files.

<img width="1110" alt="Screenshot 2023-12-15 at 17 09 49" src="https://github.com/WordPress/twentytwentyfour/assets/3593343/eb39cbc5-91cf-417d-a632-93f877275ec9">
