### ISSUE TITLE
Using the list block seems to affect the submenu layout negatively

### ISSUE THREAD

**Issue by TinoWino** [WordPress/twentytwentyfour#746]
**Description**
When I insert a list block on a page, the submenu layout is changed (menu items are spread out over two lines)

**Step-by-step reproduction instructions**
1. Make sure your site has a menu with submenu items. View it on a desktop (so not the mobile menu)
2. Create a new page. Add a paragraph.
3. Save the page, then view it. Nothing wrong with the menu / submenu items.
4. Open the page, add a list block to it with one or two items.
5. Save the page again, then view it. Now the submenu layout is changed.

**Expected behavior**
Using the list block the submenu layout should not be affected.

**Screenshots**
This is the expected behavior
![image](https://github.com/WordPress/twentytwentyfour/assets/156956222/a00be0bc-3178-4823-9c77-613d34ebb629)

This is with a page containing a list block and the submenu layout is affected
![image](https://github.com/WordPress/twentytwentyfour/assets/156956222/afb7e4bd-5b2e-43f4-ab76-be0240b80fd8)

The list block is not in the screenshot but further down the page. But this shows the way in which the submenu layout is affected.

**Environment info**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Additional context**
Reproduce the issue on www.gaypiemonte.com (the pages that use the list block are under the Rooms menu item. For example Rooms -> Suite Il Torchio).

Kudos for a truly amazing theme, thanks in advance for any help and sorry for any mistakes in my English, it is not my native language.

Kind regards,

Martijn

**Comment by carolinan** [comment]
Hi,
I am not able to reproduce this, can you add any more details and reproduction steps?
The screenshots does not show the default styles for the navigation.  it looks like you have added some custom styling, which we are unable to help with.
