### ISSUE TITLE
Block Patterns

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwentyfour#8]
There is a selection of patterns in the Figma file, which need to be added to the theme:

- [x] #107
- [x] #108
- [x] #110
- [x] #111
- [x] #112
- [x] #113
- [x] #114
- [x] #115
- [x] Columns
- [x] #116
- [x] #117
- [x] #118
- [x] #119
- [x] Left Aligned Call to Action with Image
- [x] #120
- [x] #121
- [x] Centered Statement
- [x] #122
- [x] #123
- [x] #124
- [x] #125
- [x] About

**Comment by chrisdesrochers** [comment]
I'm working on **Left Aligned Call to Action with Image**

**Comment by amedv** [comment]
**About** block pattern

```
<?php
/**
 * Title: About
 * Slug: twentytwentyfour/about
 * Categories: about
 */

?>

<!-- wp:paragraph {"align":"center","style":{"typography":{"fontStyle":"italic","fontWeight":"400","lineHeight":"1.3"},"spacing":{"padding":{"top":"6.25rem","bottom":"6.25rem"}}},"backgroundColor":"base","fontSize":"large","fontFamily":"cardo"} -->
<p class="has-text-align-center has-base-background-color has-background has-cardo-font-family has-large-font-size" style="padding-top:6.25rem;padding-bottom:6.25rem;font-style:italic;font-weight:400;line-height:1.3">
    <?php
        /* Translators: WordPress link. */
        $wordpress_link = '<a href="' . esc_url( __( 'https://wordpress.org', 'twentytwentyfour' ) ) . '" rel="nofollow">' . esc_html__( 'Money Studies', 'twentytwentyfour' ) . '</a>';
        echo sprintf(
            esc_html__( 'I write about finance, management and economy, my book “%1$s” is out now.', 'twentytwentyfour' ),
            $wordpress_link
        );
    ?>
</p>
<!-- /wp:paragraph -->
```

**Comment by luminuu** [comment]
@amedv Feel free to make a pull request directly by adding a new file to the `patterns` directory. Documentation about this can be found here: https://developer.wordpress.org/themes/advanced-topics/block-patterns/

**Comment by marcelle42** [comment]
Working on teams pattern

**Comment by gnanasekaranl** [comment]
Working on Services pattern

**Comment by marcelle42** [comment]
Working on Project Description pattern.

**Comment by LynUrth** [comment]
working on centered call to action

**Comment by amedv** [comment]
**Centered Statement** block pattern

```
<!-- wp:group {"align":"wide","layout":{"type":"default"}} -->
<div class="wp-block-group alignwide"><!-- wp:paragraph {"align":"center","style":{"typography":{"lineHeight":"1.3","fontStyle":"normal","fontWeight":"400"},"spacing":{"padding":{"top":"12rem","bottom":"12rem","right":"13rem","left":"13rem"}}},"backgroundColor":"base","textColor":"contrast","fontSize":"large","fontFamily":"cardo"} -->
<p class="has-text-align-center has-contrast-color has-base-background-color has-text-color has-background has-cardo-font-family has-large-font-size" style="padding-top:12rem;padding-right:13rem;padding-bottom:12rem;padding-left:13rem;font-style:normal;font-weight:400;line-height:1.3">Queste fotografie non solo hanno catturato la bellezza fisica del <em>Piva Arts &amp; Crafts Hotel</em>, ma hanno anche trasmesso le emozioni e le sensazioni che l'hotel evoca nei suoi ospiti</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

**Comment by hiyascout** [comment]
Working on Posts with Sidebar

**Comment by marcelle42** [comment]
Submitted Project Description block pattern.

(trying to make sure I got the github part correct)

**Comment by gpotter** [comment]
Project details block follows:

<?php
/**
 * Title: Project Details Section
 * Slug: twentytwentyfour/project-details
 * Categories: featured
 */

?>

<section class="wp-block-group alignwide">
<div class="wp-block-columns are-vertically-aligned-top" style="margin-top:5em;margin-bottom:5em">
<div class="wp-block-column is-vertically-aligned-top" style="flex-basis:25%">
<p style="padding-top:2em;padding-right:4em;padding-bottom:1em;padding-left:1em;font-size:0.75rem">Il mio obiettivo ha svelato l'anima dell'hotel, catturando gli intricati dettagli artigianali dei suoi arredi.</p>
</div>



<div class="wp-block-column is-vertically-aligned-top" style="flex-basis:66.67%">
<h3 class="wp-block-heading" style="padding-top:0.5em;padding-right:0.25em;padding-bottom:1.25em;padding-left:0em;font-size:2.4rem;font-style:normal;font-weight:400;line-height:1.3">Una struttura boutique dall'atmosfera artistica, un rifugio che invita i viagjgiatori alla ricerca di un'esperienza autentica e coinvolgente.</h3>



<div class="wp-block-columns">
<div class="wp-block-column">
<div class="wp-block-columns">
<div class="wp-block-column" style="padding-right:1rem">
<p class="has-small-font-size">La mia missione era tradurre la miscela unica di arte, artigianato e bellezza naturale dell'hotel in una raccolta di fotografie evocative che risuonassero con gli spettatori e trasmettessero lo spirito di questa incantevole destinazione. Mi sono avvicinato all'incarico con l'obiettivo di catturare il carattere dell'hotel nella sua interezza.</p>
</div>



<div class="wp-block-column">
<p class="has-small-font-size">Ogni fotografia è stata meticolosamente composta per armonizzarsi con l'estetica unica dell'hotel, intrecciando senza soluzione di continuità elementi di arte e splendore naturale. Prima di mettere piede sul posto, mi sono impegnato in una ricerca completa per comprendere le sfumature architettoniche, i motivi artistici e il contesto culturale dell'hotel.</p>
</div>
</div>
</div>
</div>
</div>
</div>
</section>

**Comment by gpotter** [comment]
Project Details Block (Section) Submitted
![project-details](https://github.com/WordPress/twentytwentyfour/assets/4108921/5fbefed7-cebd-41f9-90de-06297058dbd6)

**Comment by amedv** [comment]
**Newsletter Subscription** pattern (based on **Landing Page**, after discussion on our table — renamed to closer represent content of this pattern). noticed that now all full width block squeezed after publishing (before they looked good), will open separate issue for this.

```
<?php
/**
 * Title: Newsletter Subscription
 * Slug: twentytwentyfour/newsletter-subscription
 * Categories: buttons
 */

?>

<!-- wp:group {"align":"wide","style":{"spacing":{"padding":{"top":"15rem","bottom":"15rem","right":"10rem","left":"10rem"},"blockGap":"2.5rem"}},"backgroundColor":"custom-brick","layout":{"type":"default"}} -->
<div class="wp-block-group alignwide has-custom-brick-background-color has-background" style="padding-top:15rem;padding-right:10rem;padding-bottom:15rem;padding-left:10rem"><!-- wp:image {"align":"center","id":22,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image aligncenter size-full"><img src="<?php echo esc_url( get_stylesheet_directory_uri() ); ?>/assets/images/message_icon.png" alt="" class="wp-image-22"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"align":"center","style":{"typography":{"lineHeight":"1.2","fontStyle":"normal","fontWeight":"400"}},"textColor":"contrast","fontSize":"x-large","fontFamily":"cardo"} -->
<p class="has-text-align-center has-contrast-color has-text-color has-cardo-font-family has-x-large-font-size" style="font-style:normal;font-weight:400;line-height:1.2">
    <?php
        echo esc_html__( 'Subscribe to the newsletter and stay connected with our community.', 'twentytwentyfour' );
    ?>
</p>
<!-- /wp:paragraph -->

<!-- wp:buttons {"layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons"><!-- wp:button {"textColor":"tertiary","fontSize":"small"} -->
<div class="wp-block-button has-custom-font-size has-small-font-size">
    <a class="wp-block-button__link has-tertiary-color has-text-color wp-element-button" href="#">
        <?php
            echo esc_html__( 'Subscribe', 'twentytwentyfour' );
        ?>
    </a>
</div>
<!-- /wp:button --></div>
<!-- /wp:buttons --></div>
<!-- /wp:group -->
```

**Comment by kafleg** [comment]
> **Centered Statement** block pattern
> 
> ```
> 
> <div class="wp-block-group alignwide">
> <p class="has-text-align-center has-contrast-color has-base-background-color has-text-color has-background has-cardo-font-family has-large-font-size" style="padding-top:12rem;padding-right:13rem;padding-bottom:12rem;padding-left:13rem;font-style:normal;font-weight:400;line-height:1.3">Queste fotografie non solo hanno catturato la bellezza fisica del <em>Piva Arts &amp; Crafts Hotel</em>, ma hanno anche trasmesso le emozioni e le sensazioni che l'hotel evoca nei suoi ospiti</p>
> </div>
> 
> ```

Thank you for the code. With your code, I created a PR by making pattern. https://github.com/WordPress/twentytwentyfour/pull/61

**Comment by jordesign** [comment]
I'll work on the Hero pattern

**Comment by maurodf0** [comment]
Sorry for bother all of u. Is my first time contributing to WP Theme, sorry for all my mistakes.

I'm currently  working on Project Layout and i have some problem with the space into the first column (sx one). Even if i settled the group stack as stretch item and space between i can't achive the space. How can i handle it?
Again, sorry for all the mistakes and if this is not the correct thread.

Here the code: 
```

<!-- wp:group {"style":{"color":{"background":"#222222"},"spacing":{"padding":{"top":"6rem","bottom":"6rem","left":"6rem","right":"6rem"},"blockGap":"0"},"dimensions":{"minHeight":""}},"layout":{"type":"default"}} -->
<div class="wp-block-group has-background" style="background-color:#222222;padding-top:6rem;padding-right:6rem;padding-bottom:6rem;padding-left:6rem"><!-- wp:columns {"verticalAlignment":null,"align":"wide","style":{"spacing":{"blockGap":{"top":"0","left":"6rem"}}}} -->
<div class="wp-block-columns alignwide"><!-- wp:column {"verticalAlignment":"stretch","style":{"spacing":{"padding":{"right":"0","left":"0"},"blockGap":"0"}},"layout":{"type":"default"}} -->
<div class="wp-block-column is-vertically-aligned-stretch" style="padding-right:0;padding-left:0"><!-- wp:group {"style":{"dimensions":{"minHeight":""}},"layout":{"type":"flex","orientation":"vertical","flexWrap":"wrap","verticalAlignment":"space-between","justifyContent":"stretch"}} -->
<div class="wp-block-group"><!-- wp:image {"id":43,"sizeSlug":"full","linkDestination":"none","style":{"layout":{"selfStretch":"fit","flexSize":null},"border":{"radius":"10px"}},"className":"is-style-default"} -->
<figure class="wp-block-image size-full has-custom-border is-style-default"><img src="http://tt24.local/wp-content/uploads/2023/08/image-from-rawpixel-id-3284988-jpeg-1.png" alt="" class="wp-image-43" style="border-radius:10px"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"style":{"layout":{"selfStretch":"fit","flexSize":null}},"textColor":"base"} -->
<p class="has-base-color has-text-color">Queste basi mi hanno permesso di affrontare la sessione con un profondo apprezzamento per l'identità dell'hotel e una chiara visione della storia che volevo raccontare attraverso il mio obiettivo.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"stretch"} -->
<div class="wp-block-column is-vertically-aligned-stretch"><!-- wp:group {"layout":{"type":"flex","orientation":"vertical","justifyContent":"stretch","verticalAlignment":"space-between"}} -->
<div class="wp-block-group"><!-- wp:paragraph {"style":{"spacing":{"padding":{"bottom":"9.75rem"}},"typography":{"fontSize":"0.75rem"}},"textColor":"base-2"} -->
<p class="has-base-2-color has-text-color" style="padding-bottom:9.75rem;font-size:0.75rem">Un racconto visivo di un ritiro intriso di arte, immagini che trascendono il regno delle semplici immagini.</p>
<!-- /wp:paragraph -->

<!-- wp:paragraph {"style":{"spacing":{"padding":{"bottom":"3.75rem"}}},"textColor":"base-2","fontSize":"medium"} -->
<p class="has-base-2-color has-text-color has-medium-font-size" style="padding-bottom:3.75rem">La mia missione era tradurre la miscela unica di arte, artigianato e bellezza naturale dell'hotel in una raccolta di fotografie evocative che risuonassero con gli spettatori e trasmettessero lo spirito di questa incantevole destinazione. Mi sono avvicinato all'incarico con l'obiettivo di catturare il carattere dell'hotel nella sua interezza. Ogni fotografia è diventata una testimonianza della fusione tra arte e natura, celebrando l'impegno dell'hotel per l'autenticità e la sua armoniosa convivenza con il paesaggio circostante.</p>
<!-- /wp:paragraph -->

<!-- wp:image {"id":44,"sizeSlug":"full","linkDestination":"none","style":{"border":{"radius":"10px"}}} -->
<figure class="wp-block-image size-full has-custom-border"><img src="http://tt24.local/wp-content/uploads/2023/08/image-from-rawpixel-id-430585-jpeg-1.png" alt="" class="wp-image-44" style="border-radius:10px"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->
```

**Comment by colorful-tones** [comment]
@luminuu shall we close this out? It looks like all the boxes are checked and most things are being followed up with new issues. 🤔
