### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by luminuu** [WordPress/twentytwentyfour#9]
We need to add standard templates to the theme.

Pattern | Done | Reviewed | PR (or issue)
--- | --- | --- | ---  
Home | ✅  | 🔳 | N/A
Home Writer (pattern) | ✅ | 🔳 | N/A
Home Portfolio (pattern) | ✅ | 🔳 |  N/A
Single | ✅ | 🔳 |  N/A
Single Portfolio | ✅ | 🔳 | N/A
Single with Sidebar | ✅ | 🔳 | N/A
Page | ✅ | 🔳 | N/A
Page with Sidebar | ✅ | 🔳 | N/A
Page Portfolio  | ✅ | 🔳 | N/A
Page no title | ✅ | 🔳 | N/A
Index | ✅ | 🔳 | N/A
Index Writer (pattern) | ✅ | 🔳 | N/A
Index Portfolio (pattern) | 🔳 | 🔳 | #425 (issue)
Archive | ✅ | 🔳 | N/A
Archive Writer (pattern) | ✅ | 🔳 | N/A
Archive Portfolio (pattern) | 🔳 | 🔳 | #368
Search | ✅ | 🔳 | N/A
Search Portfolio (pattern) | 🔳 | 🔳 | #426 (issue)
404 | ✅ | 🔳 | N/A

How can we achieve different default templates for each of the subjects (Entrepreneur/Business, Writer/Blogger, Photographer/Creative)?

**Comment by MaggieCabrera** [comment]
I updated this looking at the figma grid of templates. Some of the templates are going to be patterns and need to be turned into such and removed from the template list. This should be our priority for Beta 1 @luminuu

**Comment by MaggieCabrera** [comment]
The reviewed column alludes to a design review after the PRs are merged

**Comment by carolinan** [comment]
@beafialho commented on Figma that the writer search template is only for the demo. 
In this issue for the _writer_ I am asked to add all 3 patterns for the _portfolio_. https://github.com/WordPress/twentytwentyfour/pull/377#issuecomment-1721455593
This is confusing and time confusing. 
Please label all templates clearly.

**Comment by beafialho** [comment]
> @beafialho commented on Figma that the writer search template is only for the demo.
In this issue for the writer I am asked to add all 3 patterns for the portfolio. https://github.com/WordPress/twentytwentyfour/pull/377#issuecomment-1721455593
This is confusing and time confusing.
Please label all templates clearly.

@carolinan apologies about the confusion, I was sick three days ago and probably misread what you asked and replied something totally different.

To clarify, the Writing Search should be a template and it should use the _writing_ footer.

**Comment by richtabor** [comment]
> To clarify, the Writing Search should be a template and it should use the writing footer.

We need to get solid on the use of specific header/footer parts throughout templates. I'm thinking we don't, otherwise people could easily end up with different headers/footers on different pages — while trying to keep them updated. 

I suggest we have the alternate header/footer parts available for swapping out, so that they can be applied holistically to the site within a singular header/footer template part.

**Comment by MaggieCabrera** [comment]
All the templates have been merged, let's keep improving them but I'm closing the tracking issue :D
