### ISSUE TITLE
Readme: improve guidelines for block pattern creation

### ISSUE THREAD

**Issue by MaggieCabrera** [WordPress/twentytwentyfour#99]
Looking into improving the process for future default themes, we should document best practices for block pattern creation including:

- Category selection
- Hidding or showing the pattern in the inserter and why
- Dynamic URL links
- Different translation on functions and when to use which
- Use of BlockTypes and TemplateTypes

**Comment by melchoyce** [comment]
Additionally, we should have a few design guidelines:
- When to use which colors
- The spacing presets and what each is used for
- The font size presets and what each is used for

**Comment by MaggieCabrera** [comment]
does it make sense to keep the `featured` category for things like full page block patterns?

**Comment by MaggieCabrera** [comment]
- check that all images have an alt attr with the correct description
- if we are constantly assigning properties to the same block over and over again (ie: border radius to images), consider moving those properties to the theme.json
- Remove IDs from images and query blocks

**Comment by richtabor** [comment]
> does it make sense to keep the featured category for things like full page block patterns?

No, especially not for full page patterns. 

But I do think it's helpful to tag most others in Featured for now; to help keep eyes on the available patterns for testing.

**Comment by colorful-tones** [comment]
> check that all images have an alt attr with the correct description

This is heavily dependent on the direction of #44

**Comment by richtabor** [comment]
Maybe we won't need most images. 🤞

**Comment by MaggieCabrera** [comment]
It's still a good guideline to have for the feature, if ever there's a need to include an image, there needs to be an alt attr.

**Comment by MaggieCabrera** [comment]
Naming conventions:

Prefix with page- for full page patterns and with hidden- for those that are hidden from the inserter
